# Comparision of different PRNGs (Model 1)

The Python code in this notebook will load the simulation results stored in the `statistics` folder and will generate the tables for model 1 shown in the report.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), stats.sem(a)
    h = se * stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h, h

## Load and process data

In [3]:
data = [
    {"name": "Exponential", "file": "statistics/results1Exp.txt", "mean": 200, "std": 200},
    {"name": "Logarithmic", "file": "statistics/results1Log.txt", "mean": 200, "std": 50},
    {"name": "Gamma", "file": "statistics/results1Gamma.txt", "mean": 200, "std": 50},
    {"name": "Triangular", "file": "statistics/results1Triangular.txt", "mean": 200, "std": 50}
]

In [4]:
for i in range(len(data)):
    data[i]["df"] = pd.read_csv(data[i]["file"], header=None, names=["rng_mode", "n", "mean", "std", "delta2", "time"], sep="\t")

In [5]:
generators=data[0]["df"]["rng_mode"].drop_duplicates().tolist()
generators.remove("ThreadLocalRandomSlow")  # This is the same a "ThreadLocalRandom". Only used for speed comparision. Removed from other tables.

In [6]:
for rec in data:
    df = rec["df"]
    mean = rec["mean"]
    std = rec["std"]

    mean_error = []
    std_error = []
    delta2 = []
    time = []

    for generator in generators:
        mean_error.append(round(abs(df[df["rng_mode"] == generator]["mean"].mean() - mean) / mean * 100, 5))  # Values are in percentage
        std_error.append(round(abs(df[df["rng_mode"] == generator]["std"].mean() - std) / std * 100, 5))  # Values are in percentage
        delta2.append(round(df[df["rng_mode"] == generator]["delta2"].mean() * 100000000, 5))
        time.append(round(df[df["rng_mode"] == generator]["time"].mean(), 5))

    rec["mean_error"] = mean_error
    rec["std_error"] = std_error
    rec["delta2"] = delta2
    rec["time"] = time

## Mean (not used in the report)

In [7]:
d = {}
for rec in data:
    d[rec["name"]] = rec["mean_error"]

df_mean = pd.DataFrame(d, index=generators)

df_mean

                   Exponential  Logarithmic    Gamma  Triangular
ThreadLocalRandom      0.00009      0.00049  0.00013     0.00003
Random                 0.00170      0.00012  0.00100     0.00015
SecureRandom           0.00055      0.00065  0.00010     0.00014
Well512a               0.00099      0.00021  0.00021     0.00028
Well1024a              0.00100      0.00010  0.00038     0.00017
Well19937a             0.00056      0.00063  0.00009     0.00050
Well19937c             0.00101      0.00022  0.00009     0.00041
Well44497a             0.00056      0.00018  0.00080     0.00008
Well44497b             0.00049      0.00029  0.00019     0.00088
MersenneTwister        0.00014      0.00031  0.00066     0.00023
ISAAC                  0.00008      0.00021  0.00024     0.00027
XoRoShiRo128++         0.00062      0.00005  0.00048     0.00001
XoRoShiRo128**         0.00109      0.00025  0.00078     0.00018
XoRoShiRo64**          0.00022      0.00002  0.00003     0.00038
XoRoShiRo256++         0.00063      0.00003  0.00025     0.00052
XoRoShiRo1024++        0.00006      0.00041  0.00050     0.00032
XoRoShiRo1024*         0.00061      0.00034  0.00002     0.00043
XoRoShiRo1024**        0.00049      0.00045  0.00016     0.00029
L32X64Mix              0.00125      0.00041  0.00004     0.00075
L64X128Mix             0.00043      0.00022  0.00024     0.00007
L64X128**              0.00174      0.00004  0.00035     0.00027
L64X256Mix             0.00111      0.00041  0.00011     0.00044
L64X1024Mix            0.00227      0.00050  0.00052     0.00015
L128X128Mix            0.00176      0.00004  0.00021     0.00027
L128X256Mix            0.00001      0.00047  0.00016     0.00018
L128X1024Mix           0.00015      0.00001  0.00030     0.00002
PcgRxsMXs64            0.00156      0.00055  0.00033     0.00030
Philox4x64             0.00057      0.00007  0.00010     0.00012
Drand48                0.00060      0.00027  0.00134     0.00046
Drand48Mix             0.00388      0.00033  0.00065     0.00123

In [8]:

s = df_mean.style.format("{:.5f}\\,\\%").set_caption("Mean Error (in \\%)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Mean Error (in \%)}
\begin{tabular}{lrrrr}
 & Exponential & Logarithmic & Gamma & Triangular \\
ThreadLocalRandom & 0.00009\,\% & 0.00049\,\% & 0.00013\,\% & 0.00003\,\% \\
Random & 0.00170\,\% & 0.00012\,\% & 0.00100\,\% & 0.00015\,\% \\
SecureRandom & 0.00055\,\% & 0.00065\,\% & 0.00010\,\% & 0.00014\,\% \\
Well512a & 0.00099\,\% & 0.00021\,\% & 0.00021\,\% & 0.00028\,\% \\
Well1024a & 0.00100\,\% & 0.00010\,\% & 0.00038\,\% & 0.00017\,\% \\
Well19937a & 0.00056\,\% & 0.00063\,\% & 0.00009\,\% & 0.00050\,\% \\
Well19937c & 0.00101\,\% & 0.00022\,\% & 0.00009\,\% & 0.00041\,\% \\
Well44497a & 0.00056\,\% & 0.00018\,\% & 0.00080\,\% & 0.00008\,\% \\
Well44497b & 0.00049\,\% & 0.00029\,\% & 0.00019\,\% & 0.00088\,\% \\
MersenneTwister & 0.00014\,\% & 0.00031\,\% & 0.00066\,\% & 0.00023\,\% \\
ISAAC & 0.00008\,\% & 0.00021\,\% & 0.00024\,\% & 0.00027\,\% \\
XoRoShiRo128++ & 0.00062\,\% & 0.00005\,\% & 0.00048\,\% & 0.00001\,\% \\
XoRoShiRo128** & 0.00109\,\% & 0.00025\,\% & 0.00078\,\% & 0.00018\,\% \\
XoRoShiRo64** & 0.00022\,\% & 0.00002\,\% & 0.00003\,\% & 0.00038\,\% \\
XoRoShiRo256++ & 0.00063\,\% & 0.00003\,\% & 0.00025\,\% & 0.00052\,\% \\
XoRoShiRo1024++ & 0.00006\,\% & 0.00041\,\% & 0.00050\,\% & 0.00032\,\% \\
XoRoShiRo1024* & 0.00061\,\% & 0.00034\,\% & 0.00002\,\% & 0.00043\,\% \\
XoRoShiRo1024** & 0.00049\,\% & 0.00045\,\% & 0.00016\,\% & 0.00029\,\% \\
L32X64Mix & 0.00125\,\% & 0.00041\,\% & 0.00004\,\% & 0.00075\,\% \\
L64X128Mix & 0.00043\,\% & 0.00022\,\% & 0.00024\,\% & 0.00007\,\% \\
L64X128** & 0.00174\,\% & 0.00004\,\% & 0.00035\,\% & 0.00027\,\% \\
L64X256Mix & 0.00111\,\% & 0.00041\,\% & 0.00011\,\% & 0.00044\,\% \\
L64X1024Mix & 0.00227\,\% & 0.00050\,\% & 0.00052\,\% & 0.00015\,\% \\
L128X128Mix & 0.00176\,\% & 0.00004\,\% & 0.00021\,\% & 0.00027\,\% \\
L128X256Mix & 0.00001\,\% & 0.00047\,\% & 0.00016\,\% & 0.00018\,\% \\
L128X1024Mix & 0.00015\,\% & 0.00001\,\% & 0.00030\,\% & 0.00002\,\% \\
PcgRxsMXs64 & 0.00156\,\% & 0.00055\,\% & 0.00033\,\% & 0.00030\,\% \\
Philox4x64 & 0.00057\,\% & 0.00007\,\% & 0.00010\,\% & 0.00012\,\% \\
Drand48 & 0.00060\,\% & 0.00027\,\% & 0.00134\,\% & 0.00046\,\% \\
Drand48Mix & 0.00388\,\% & 0.00033\,\% & 0.00065\,\% & 0.00123\,\% \\
\end{tabular}
\end{table}

In [9]:
s = df_mean.style.format("{:.5f}%").set_caption("Mean Error (in %)")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_9cdd9">
  <caption>Mean Error (in %)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_9cdd9_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_9cdd9_level0_col1" class="col_heading level0 col1" >Logarithmic</th>
      <th id="T_9cdd9_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_9cdd9_level0_col3" class="col_heading level0 col3" >Triangular</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_9cdd9_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_9cdd9_row0_col0" class="data row0 col0" >0.00009%</td>
      <td id="T_9cdd9_row0_col1" class="data row0 col1" >0.00049%</td>
      <td id="T_9cdd9_row0_col2" class="data row0 col2" >0.00013%</td>
      <td id="T_9cdd9_row0_col3" class="data row0 col3" >0.00003%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_9cdd9_row1_col0" class="data row1 col0" >0.00170%</td>
      <td id="T_9cdd9_row1_col1" class="data row1 col1" >0.00012%</td>
      <td id="T_9cdd9_row1_col2" class="data row1 col2" >0.00100%</td>
      <td id="T_9cdd9_row1_col3" class="data row1 col3" >0.00015%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_9cdd9_row2_col0" class="data row2 col0" >0.00055%</td>
      <td id="T_9cdd9_row2_col1" class="data row2 col1" >0.00065%</td>
      <td id="T_9cdd9_row2_col2" class="data row2 col2" >0.00010%</td>
      <td id="T_9cdd9_row2_col3" class="data row2 col3" >0.00014%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_9cdd9_row3_col0" class="data row3 col0" >0.00099%</td>
      <td id="T_9cdd9_row3_col1" class="data row3 col1" >0.00021%</td>
      <td id="T_9cdd9_row3_col2" class="data row3 col2" >0.00021%</td>
      <td id="T_9cdd9_row3_col3" class="data row3 col3" >0.00028%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_9cdd9_row4_col0" class="data row4 col0" >0.00100%</td>
      <td id="T_9cdd9_row4_col1" class="data row4 col1" >0.00010%</td>
      <td id="T_9cdd9_row4_col2" class="data row4 col2" >0.00038%</td>
      <td id="T_9cdd9_row4_col3" class="data row4 col3" >0.00017%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_9cdd9_row5_col0" class="data row5 col0" >0.00056%</td>
      <td id="T_9cdd9_row5_col1" class="data row5 col1" >0.00063%</td>
      <td id="T_9cdd9_row5_col2" class="data row5 col2" >0.00009%</td>
      <td id="T_9cdd9_row5_col3" class="data row5 col3" >0.00050%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_9cdd9_row6_col0" class="data row6 col0" >0.00101%</td>
      <td id="T_9cdd9_row6_col1" class="data row6 col1" >0.00022%</td>
      <td id="T_9cdd9_row6_col2" class="data row6 col2" >0.00009%</td>
      <td id="T_9cdd9_row6_col3" class="data row6 col3" >0.00041%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_9cdd9_row7_col0" class="data row7 col0" >0.00056%</td>
      <td id="T_9cdd9_row7_col1" class="data row7 col1" >0.00018%</td>
      <td id="T_9cdd9_row7_col2" class="data row7 col2" >0.00080%</td>
      <td id="T_9cdd9_row7_col3" class="data row7 col3" >0.00008%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_9cdd9_row8_col0" class="data row8 col0" >0.00049%</td>
      <td id="T_9cdd9_row8_col1" class="data row8 col1" >0.00029%</td>
      <td id="T_9cdd9_row8_col2" class="data row8 col2" >0.00019%</td>
      <td id="T_9cdd9_row8_col3" class="data row8 col3" >0.00088%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_9cdd9_row9_col0" class="data row9 col0" >0.00014%</td>
      <td id="T_9cdd9_row9_col1" class="data row9 col1" >0.00031%</td>
      <td id="T_9cdd9_row9_col2" class="data row9 col2" >0.00066%</td>
      <td id="T_9cdd9_row9_col3" class="data row9 col3" >0.00023%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row10" class="row_heading level0 row10" >ISAAC</th>
      <td id="T_9cdd9_row10_col0" class="data row10 col0" >0.00008%</td>
      <td id="T_9cdd9_row10_col1" class="data row10 col1" >0.00021%</td>
      <td id="T_9cdd9_row10_col2" class="data row10 col2" >0.00024%</td>
      <td id="T_9cdd9_row10_col3" class="data row10 col3" >0.00027%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row11" class="row_heading level0 row11" >XoRoShiRo128++</th>
      <td id="T_9cdd9_row11_col0" class="data row11 col0" >0.00062%</td>
      <td id="T_9cdd9_row11_col1" class="data row11 col1" >0.00005%</td>
      <td id="T_9cdd9_row11_col2" class="data row11 col2" >0.00048%</td>
      <td id="T_9cdd9_row11_col3" class="data row11 col3" >0.00001%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row12" class="row_heading level0 row12" >XoRoShiRo128**</th>
      <td id="T_9cdd9_row12_col0" class="data row12 col0" >0.00109%</td>
      <td id="T_9cdd9_row12_col1" class="data row12 col1" >0.00025%</td>
      <td id="T_9cdd9_row12_col2" class="data row12 col2" >0.00078%</td>
      <td id="T_9cdd9_row12_col3" class="data row12 col3" >0.00018%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row13" class="row_heading level0 row13" >XoRoShiRo64**</th>
      <td id="T_9cdd9_row13_col0" class="data row13 col0" >0.00022%</td>
      <td id="T_9cdd9_row13_col1" class="data row13 col1" >0.00002%</td>
      <td id="T_9cdd9_row13_col2" class="data row13 col2" >0.00003%</td>
      <td id="T_9cdd9_row13_col3" class="data row13 col3" >0.00038%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row14" class="row_heading level0 row14" >XoRoShiRo256++</th>
      <td id="T_9cdd9_row14_col0" class="data row14 col0" >0.00063%</td>
      <td id="T_9cdd9_row14_col1" class="data row14 col1" >0.00003%</td>
      <td id="T_9cdd9_row14_col2" class="data row14 col2" >0.00025%</td>
      <td id="T_9cdd9_row14_col3" class="data row14 col3" >0.00052%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row15" class="row_heading level0 row15" >XoRoShiRo1024++</th>
      <td id="T_9cdd9_row15_col0" class="data row15 col0" >0.00006%</td>
      <td id="T_9cdd9_row15_col1" class="data row15 col1" >0.00041%</td>
      <td id="T_9cdd9_row15_col2" class="data row15 col2" >0.00050%</td>
      <td id="T_9cdd9_row15_col3" class="data row15 col3" >0.00032%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024*</th>
      <td id="T_9cdd9_row16_col0" class="data row16 col0" >0.00061%</td>
      <td id="T_9cdd9_row16_col1" class="data row16 col1" >0.00034%</td>
      <td id="T_9cdd9_row16_col2" class="data row16 col2" >0.00002%</td>
      <td id="T_9cdd9_row16_col3" class="data row16 col3" >0.00043%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024**</th>
      <td id="T_9cdd9_row17_col0" class="data row17 col0" >0.00049%</td>
      <td id="T_9cdd9_row17_col1" class="data row17 col1" >0.00045%</td>
      <td id="T_9cdd9_row17_col2" class="data row17 col2" >0.00016%</td>
      <td id="T_9cdd9_row17_col3" class="data row17 col3" >0.00029%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row18" class="row_heading level0 row18" >L32X64Mix</th>
      <td id="T_9cdd9_row18_col0" class="data row18 col0" >0.00125%</td>
      <td id="T_9cdd9_row18_col1" class="data row18 col1" >0.00041%</td>
      <td id="T_9cdd9_row18_col2" class="data row18 col2" >0.00004%</td>
      <td id="T_9cdd9_row18_col3" class="data row18 col3" >0.00075%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row19" class="row_heading level0 row19" >L64X128Mix</th>
      <td id="T_9cdd9_row19_col0" class="data row19 col0" >0.00043%</td>
      <td id="T_9cdd9_row19_col1" class="data row19 col1" >0.00022%</td>
      <td id="T_9cdd9_row19_col2" class="data row19 col2" >0.00024%</td>
      <td id="T_9cdd9_row19_col3" class="data row19 col3" >0.00007%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row20" class="row_heading level0 row20" >L64X128**</th>
      <td id="T_9cdd9_row20_col0" class="data row20 col0" >0.00174%</td>
      <td id="T_9cdd9_row20_col1" class="data row20 col1" >0.00004%</td>
      <td id="T_9cdd9_row20_col2" class="data row20 col2" >0.00035%</td>
      <td id="T_9cdd9_row20_col3" class="data row20 col3" >0.00027%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row21" class="row_heading level0 row21" >L64X256Mix</th>
      <td id="T_9cdd9_row21_col0" class="data row21 col0" >0.00111%</td>
      <td id="T_9cdd9_row21_col1" class="data row21 col1" >0.00041%</td>
      <td id="T_9cdd9_row21_col2" class="data row21 col2" >0.00011%</td>
      <td id="T_9cdd9_row21_col3" class="data row21 col3" >0.00044%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row22" class="row_heading level0 row22" >L64X1024Mix</th>
      <td id="T_9cdd9_row22_col0" class="data row22 col0" >0.00227%</td>
      <td id="T_9cdd9_row22_col1" class="data row22 col1" >0.00050%</td>
      <td id="T_9cdd9_row22_col2" class="data row22 col2" >0.00052%</td>
      <td id="T_9cdd9_row22_col3" class="data row22 col3" >0.00015%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row23" class="row_heading level0 row23" >L128X128Mix</th>
      <td id="T_9cdd9_row23_col0" class="data row23 col0" >0.00176%</td>
      <td id="T_9cdd9_row23_col1" class="data row23 col1" >0.00004%</td>
      <td id="T_9cdd9_row23_col2" class="data row23 col2" >0.00021%</td>
      <td id="T_9cdd9_row23_col3" class="data row23 col3" >0.00027%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row24" class="row_heading level0 row24" >L128X256Mix</th>
      <td id="T_9cdd9_row24_col0" class="data row24 col0" >0.00001%</td>
      <td id="T_9cdd9_row24_col1" class="data row24 col1" >0.00047%</td>
      <td id="T_9cdd9_row24_col2" class="data row24 col2" >0.00016%</td>
      <td id="T_9cdd9_row24_col3" class="data row24 col3" >0.00018%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row25" class="row_heading level0 row25" >L128X1024Mix</th>
      <td id="T_9cdd9_row25_col0" class="data row25 col0" >0.00015%</td>
      <td id="T_9cdd9_row25_col1" class="data row25 col1" >0.00001%</td>
      <td id="T_9cdd9_row25_col2" class="data row25 col2" >0.00030%</td>
      <td id="T_9cdd9_row25_col3" class="data row25 col3" >0.00002%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row26" class="row_heading level0 row26" >PcgRxsMXs64</th>
      <td id="T_9cdd9_row26_col0" class="data row26 col0" >0.00156%</td>
      <td id="T_9cdd9_row26_col1" class="data row26 col1" >0.00055%</td>
      <td id="T_9cdd9_row26_col2" class="data row26 col2" >0.00033%</td>
      <td id="T_9cdd9_row26_col3" class="data row26 col3" >0.00030%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row27" class="row_heading level0 row27" >Philox4x64</th>
      <td id="T_9cdd9_row27_col0" class="data row27 col0" >0.00057%</td>
      <td id="T_9cdd9_row27_col1" class="data row27 col1" >0.00007%</td>
      <td id="T_9cdd9_row27_col2" class="data row27 col2" >0.00010%</td>
      <td id="T_9cdd9_row27_col3" class="data row27 col3" >0.00012%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row28" class="row_heading level0 row28" >Drand48</th>
      <td id="T_9cdd9_row28_col0" class="data row28 col0" >0.00060%</td>
      <td id="T_9cdd9_row28_col1" class="data row28 col1" >0.00027%</td>
      <td id="T_9cdd9_row28_col2" class="data row28 col2" >0.00134%</td>
      <td id="T_9cdd9_row28_col3" class="data row28 col3" >0.00046%</td>
    </tr>
    <tr>
      <th id="T_9cdd9_level0_row29" class="row_heading level0 row29" >Drand48Mix</th>
      <td id="T_9cdd9_row29_col0" class="data row29 col0" >0.00388%</td>
      <td id="T_9cdd9_row29_col1" class="data row29 col1" >0.00033%</td>
      <td id="T_9cdd9_row29_col2" class="data row29 col2" >0.00065%</td>
      <td id="T_9cdd9_row29_col3" class="data row29 col3" >0.00123%</td>
    </tr>
  </tbody>
</table>

### Maximum mean error per column

In [10]:
df_mean.max()

Exponential    0.00388
Logarithmic    0.00065
Gamma          0.00134
Triangular     0.00123
dtype: float64

### Confidence interval for mean

In [30]:
conf = {}
h_list = []
for rec in data:
    name = rec["name"]
    df = rec["df"]
    for generator in generators:
        l = list(df[df["rng_mode"] == generator]["mean"])
        h = mean_confidence_interval(l)[3]  # 95%
        if name not in conf: conf[name] = []
        conf[name].append(h)
        h_list.append(h)

df_conf = pd.DataFrame(conf, index=generators)
df_conf

                       Exponential  Logarithmic     Gamma  Triangular
ThreadLocalRandom         0.004344     0.000981  0.001004    0.001043
Random                    0.003994     0.000966  0.000976    0.000960
SecureRandom              0.004455     0.001022  0.000968    0.000968
Well512a                  0.003979     0.000958  0.001084    0.000840
Well1024a                 0.003627     0.000943  0.001049    0.001062
Well19937a                0.003990     0.001042  0.001128    0.001077
Well19937c                0.004308     0.000930  0.001133    0.000994
Well44497a                0.004549     0.001003  0.001065    0.000982
Well44497b                0.003732     0.000954  0.000925    0.000917
MersenneTwister           0.004342     0.000920  0.000947    0.001031
ISAAC                     0.003923     0.000920  0.000962    0.000873
XoRoShiRo128++            0.004229     0.000965  0.001003    0.000919
XoRoShiRo128**            0.004065     0.001130  0.000952    0.000959
XoRoShiRo64**             0.004022     0.001078  0.001048    0.001066
XoRoShiRo256++            0.003654     0.000925  0.000973    0.001066
XoRoShiRo1024++           0.003851     0.001016  0.000993    0.001046
XoRoShiRo1024*            0.004798     0.001045  0.001010    0.001009
XoRoShiRo1024**           0.003444     0.001062  0.001124    0.001011
L32X64Mix                 0.004162     0.000992  0.001047    0.000849
L64X128Mix                0.004173     0.000933  0.001011    0.000994
L64X128**                 0.003737     0.000991  0.001083    0.000955
L64X256Mix                0.004254     0.000991  0.000984    0.000920
L64X1024Mix               0.003911     0.000991  0.000986    0.001023
L128X128Mix               0.003729     0.001045  0.000960    0.000923
L128X256Mix               0.004067     0.001001  0.001011    0.000894
L128X1024Mix              0.004376     0.000810  0.001042    0.000961
PcgRxsMXs64               0.004355     0.001049  0.001079    0.001041
Philox4x64                0.004096     0.000962  0.000992    0.000993
Drand48                   0.016000     0.004170  0.004073    0.004156
Drand48Mix                0.017075     0.004434  0.004334    0.004254
ThreadLocalRandomSlow     0.003799     0.001064  0.001032    0.000927

In [32]:
print(df_conf[~df_conf.index.isin(["Drand48", "Drand48Mix"])].max())

print(df_conf[df_conf.index.isin(["Drand48", "Drand48Mix"])].max())

Exponential    0.004798
Logarithmic    0.001130
Gamma          0.001133
Triangular     0.001077
dtype: float64
Exponential    0.017075
Logarithmic    0.004434
Gamma          0.004334
Triangular     0.004254
dtype: float64

## Standard deviation

In [13]:
d = {}
for rec in data:
    d[rec["name"]] = rec["std_error"]

df_std = pd.DataFrame(d, index=generators)

df_std

                   Exponential  Logarithmic    Gamma  Triangular
ThreadLocalRandom      0.00043      0.00130  0.00004     0.00134
Random                 0.00149      0.00039  0.00191     0.00166
SecureRandom           0.00077      0.00384  0.00062     0.00219
Well512a               0.00049      0.00144  0.00343     0.00262
Well1024a              0.00195      0.00268  0.00073     0.00219
Well19937a             0.00008      0.00151  0.00106     0.00164
Well19937c             0.00212      0.00023  0.00045     0.00136
Well44497a             0.00244      0.00365  0.00137     0.00206
Well44497b             0.00154      0.00158  0.00223     0.00215
MersenneTwister        0.00023      0.00319  0.00309     0.00299
ISAAC                  0.00078      0.00067  0.00164     0.00175
XoRoShiRo128++         0.00076      0.00133  0.00250     0.00216
XoRoShiRo128**         0.00035      0.00094  0.00186     0.00165
XoRoShiRo64**          0.00153      0.00139  0.00057     0.00113
XoRoShiRo256++         0.00070      0.00172  0.00358     0.00097
XoRoShiRo1024++        0.00154      0.00171  0.00183     0.00147
XoRoShiRo1024*         0.00088      0.00152  0.00073     0.00037
XoRoShiRo1024**        0.00030      0.00196  0.00195     0.00182
L32X64Mix              0.00202      0.00222  0.00089     0.00114
L64X128Mix             0.00036      0.00122  0.00243     0.00212
L64X128**              0.00021      0.00075  0.00334     0.00155
L64X256Mix             0.00219      0.00182  0.00150     0.00127
L64X1024Mix            0.00144      0.00300  0.00241     0.00270
L128X128Mix            0.00138      0.00113  0.00117     0.00244
L128X256Mix            0.00005      0.00260  0.00124     0.00148
L128X1024Mix           0.00081      0.00194  0.00170     0.00265
PcgRxsMXs64            0.00103      0.00058  0.00144     0.00286
Philox4x64             0.00103      0.00263  0.00071     0.00144
Drand48                0.00844      0.00301  0.00764     0.00359
Drand48Mix             0.00864      0.00775  0.00484     0.00858

In [14]:
s = df_std.style.format("{:.3f}\\,\\%").set_caption("Standard Deviation Error (in \\%)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Standard Deviation Error (in \%)}
\begin{tabular}{lrrrr}
 & Exponential & Logarithmic & Gamma & Triangular \\
ThreadLocalRandom & 0.000\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% \\
Random & 0.001\,\% & 0.000\,\% & 0.002\,\% & 0.002\,\% \\
SecureRandom & 0.001\,\% & 0.004\,\% & 0.001\,\% & 0.002\,\% \\
Well512a & 0.000\,\% & 0.001\,\% & 0.003\,\% & 0.003\,\% \\
Well1024a & 0.002\,\% & 0.003\,\% & 0.001\,\% & 0.002\,\% \\
Well19937a & 0.000\,\% & 0.002\,\% & 0.001\,\% & 0.002\,\% \\
Well19937c & 0.002\,\% & 0.000\,\% & 0.000\,\% & 0.001\,\% \\
Well44497a & 0.002\,\% & 0.004\,\% & 0.001\,\% & 0.002\,\% \\
Well44497b & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.002\,\% \\
MersenneTwister & 0.000\,\% & 0.003\,\% & 0.003\,\% & 0.003\,\% \\
ISAAC & 0.001\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% \\
XoRoShiRo128++ & 0.001\,\% & 0.001\,\% & 0.003\,\% & 0.002\,\% \\
XoRoShiRo128** & 0.000\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% \\
XoRoShiRo64** & 0.002\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% \\
XoRoShiRo256++ & 0.001\,\% & 0.002\,\% & 0.004\,\% & 0.001\,\% \\
XoRoShiRo1024++ & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% \\
XoRoShiRo1024* & 0.001\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% \\
XoRoShiRo1024** & 0.000\,\% & 0.002\,\% & 0.002\,\% & 0.002\,\% \\
L32X64Mix & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.001\,\% \\
L64X128Mix & 0.000\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% \\
L64X128** & 0.000\,\% & 0.001\,\% & 0.003\,\% & 0.002\,\% \\
L64X256Mix & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% \\
L64X1024Mix & 0.001\,\% & 0.003\,\% & 0.002\,\% & 0.003\,\% \\
L128X128Mix & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.002\,\% \\
L128X256Mix & 0.000\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% \\
L128X1024Mix & 0.001\,\% & 0.002\,\% & 0.002\,\% & 0.003\,\% \\
PcgRxsMXs64 & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.003\,\% \\
Philox4x64 & 0.001\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% \\
Drand48 & 0.008\,\% & 0.003\,\% & 0.008\,\% & 0.004\,\% \\
Drand48Mix & 0.009\,\% & 0.008\,\% & 0.005\,\% & 0.009\,\% \\
\end{tabular}
\end{table}

In [15]:
s = df_std.style.format("{:.3f}%").set_caption("Standard Deviation Error (in %)")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_3d1c5">
  <caption>Standard Deviation Error (in %)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_3d1c5_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_3d1c5_level0_col1" class="col_heading level0 col1" >Logarithmic</th>
      <th id="T_3d1c5_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_3d1c5_level0_col3" class="col_heading level0 col3" >Triangular</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_3d1c5_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_3d1c5_row0_col0" class="data row0 col0" >0.000%</td>
      <td id="T_3d1c5_row0_col1" class="data row0 col1" >0.001%</td>
      <td id="T_3d1c5_row0_col2" class="data row0 col2" >0.000%</td>
      <td id="T_3d1c5_row0_col3" class="data row0 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_3d1c5_row1_col0" class="data row1 col0" >0.001%</td>
      <td id="T_3d1c5_row1_col1" class="data row1 col1" >0.000%</td>
      <td id="T_3d1c5_row1_col2" class="data row1 col2" >0.002%</td>
      <td id="T_3d1c5_row1_col3" class="data row1 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_3d1c5_row2_col0" class="data row2 col0" >0.001%</td>
      <td id="T_3d1c5_row2_col1" class="data row2 col1" >0.004%</td>
      <td id="T_3d1c5_row2_col2" class="data row2 col2" >0.001%</td>
      <td id="T_3d1c5_row2_col3" class="data row2 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_3d1c5_row3_col0" class="data row3 col0" >0.000%</td>
      <td id="T_3d1c5_row3_col1" class="data row3 col1" >0.001%</td>
      <td id="T_3d1c5_row3_col2" class="data row3 col2" >0.003%</td>
      <td id="T_3d1c5_row3_col3" class="data row3 col3" >0.003%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_3d1c5_row4_col0" class="data row4 col0" >0.002%</td>
      <td id="T_3d1c5_row4_col1" class="data row4 col1" >0.003%</td>
      <td id="T_3d1c5_row4_col2" class="data row4 col2" >0.001%</td>
      <td id="T_3d1c5_row4_col3" class="data row4 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_3d1c5_row5_col0" class="data row5 col0" >0.000%</td>
      <td id="T_3d1c5_row5_col1" class="data row5 col1" >0.002%</td>
      <td id="T_3d1c5_row5_col2" class="data row5 col2" >0.001%</td>
      <td id="T_3d1c5_row5_col3" class="data row5 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_3d1c5_row6_col0" class="data row6 col0" >0.002%</td>
      <td id="T_3d1c5_row6_col1" class="data row6 col1" >0.000%</td>
      <td id="T_3d1c5_row6_col2" class="data row6 col2" >0.000%</td>
      <td id="T_3d1c5_row6_col3" class="data row6 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_3d1c5_row7_col0" class="data row7 col0" >0.002%</td>
      <td id="T_3d1c5_row7_col1" class="data row7 col1" >0.004%</td>
      <td id="T_3d1c5_row7_col2" class="data row7 col2" >0.001%</td>
      <td id="T_3d1c5_row7_col3" class="data row7 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_3d1c5_row8_col0" class="data row8 col0" >0.002%</td>
      <td id="T_3d1c5_row8_col1" class="data row8 col1" >0.002%</td>
      <td id="T_3d1c5_row8_col2" class="data row8 col2" >0.002%</td>
      <td id="T_3d1c5_row8_col3" class="data row8 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_3d1c5_row9_col0" class="data row9 col0" >0.000%</td>
      <td id="T_3d1c5_row9_col1" class="data row9 col1" >0.003%</td>
      <td id="T_3d1c5_row9_col2" class="data row9 col2" >0.003%</td>
      <td id="T_3d1c5_row9_col3" class="data row9 col3" >0.003%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row10" class="row_heading level0 row10" >ISAAC</th>
      <td id="T_3d1c5_row10_col0" class="data row10 col0" >0.001%</td>
      <td id="T_3d1c5_row10_col1" class="data row10 col1" >0.001%</td>
      <td id="T_3d1c5_row10_col2" class="data row10 col2" >0.002%</td>
      <td id="T_3d1c5_row10_col3" class="data row10 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row11" class="row_heading level0 row11" >XoRoShiRo128++</th>
      <td id="T_3d1c5_row11_col0" class="data row11 col0" >0.001%</td>
      <td id="T_3d1c5_row11_col1" class="data row11 col1" >0.001%</td>
      <td id="T_3d1c5_row11_col2" class="data row11 col2" >0.003%</td>
      <td id="T_3d1c5_row11_col3" class="data row11 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row12" class="row_heading level0 row12" >XoRoShiRo128**</th>
      <td id="T_3d1c5_row12_col0" class="data row12 col0" >0.000%</td>
      <td id="T_3d1c5_row12_col1" class="data row12 col1" >0.001%</td>
      <td id="T_3d1c5_row12_col2" class="data row12 col2" >0.002%</td>
      <td id="T_3d1c5_row12_col3" class="data row12 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row13" class="row_heading level0 row13" >XoRoShiRo64**</th>
      <td id="T_3d1c5_row13_col0" class="data row13 col0" >0.002%</td>
      <td id="T_3d1c5_row13_col1" class="data row13 col1" >0.001%</td>
      <td id="T_3d1c5_row13_col2" class="data row13 col2" >0.001%</td>
      <td id="T_3d1c5_row13_col3" class="data row13 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row14" class="row_heading level0 row14" >XoRoShiRo256++</th>
      <td id="T_3d1c5_row14_col0" class="data row14 col0" >0.001%</td>
      <td id="T_3d1c5_row14_col1" class="data row14 col1" >0.002%</td>
      <td id="T_3d1c5_row14_col2" class="data row14 col2" >0.004%</td>
      <td id="T_3d1c5_row14_col3" class="data row14 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row15" class="row_heading level0 row15" >XoRoShiRo1024++</th>
      <td id="T_3d1c5_row15_col0" class="data row15 col0" >0.002%</td>
      <td id="T_3d1c5_row15_col1" class="data row15 col1" >0.002%</td>
      <td id="T_3d1c5_row15_col2" class="data row15 col2" >0.002%</td>
      <td id="T_3d1c5_row15_col3" class="data row15 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024*</th>
      <td id="T_3d1c5_row16_col0" class="data row16 col0" >0.001%</td>
      <td id="T_3d1c5_row16_col1" class="data row16 col1" >0.002%</td>
      <td id="T_3d1c5_row16_col2" class="data row16 col2" >0.001%</td>
      <td id="T_3d1c5_row16_col3" class="data row16 col3" >0.000%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024**</th>
      <td id="T_3d1c5_row17_col0" class="data row17 col0" >0.000%</td>
      <td id="T_3d1c5_row17_col1" class="data row17 col1" >0.002%</td>
      <td id="T_3d1c5_row17_col2" class="data row17 col2" >0.002%</td>
      <td id="T_3d1c5_row17_col3" class="data row17 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row18" class="row_heading level0 row18" >L32X64Mix</th>
      <td id="T_3d1c5_row18_col0" class="data row18 col0" >0.002%</td>
      <td id="T_3d1c5_row18_col1" class="data row18 col1" >0.002%</td>
      <td id="T_3d1c5_row18_col2" class="data row18 col2" >0.001%</td>
      <td id="T_3d1c5_row18_col3" class="data row18 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row19" class="row_heading level0 row19" >L64X128Mix</th>
      <td id="T_3d1c5_row19_col0" class="data row19 col0" >0.000%</td>
      <td id="T_3d1c5_row19_col1" class="data row19 col1" >0.001%</td>
      <td id="T_3d1c5_row19_col2" class="data row19 col2" >0.002%</td>
      <td id="T_3d1c5_row19_col3" class="data row19 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row20" class="row_heading level0 row20" >L64X128**</th>
      <td id="T_3d1c5_row20_col0" class="data row20 col0" >0.000%</td>
      <td id="T_3d1c5_row20_col1" class="data row20 col1" >0.001%</td>
      <td id="T_3d1c5_row20_col2" class="data row20 col2" >0.003%</td>
      <td id="T_3d1c5_row20_col3" class="data row20 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row21" class="row_heading level0 row21" >L64X256Mix</th>
      <td id="T_3d1c5_row21_col0" class="data row21 col0" >0.002%</td>
      <td id="T_3d1c5_row21_col1" class="data row21 col1" >0.002%</td>
      <td id="T_3d1c5_row21_col2" class="data row21 col2" >0.002%</td>
      <td id="T_3d1c5_row21_col3" class="data row21 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row22" class="row_heading level0 row22" >L64X1024Mix</th>
      <td id="T_3d1c5_row22_col0" class="data row22 col0" >0.001%</td>
      <td id="T_3d1c5_row22_col1" class="data row22 col1" >0.003%</td>
      <td id="T_3d1c5_row22_col2" class="data row22 col2" >0.002%</td>
      <td id="T_3d1c5_row22_col3" class="data row22 col3" >0.003%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row23" class="row_heading level0 row23" >L128X128Mix</th>
      <td id="T_3d1c5_row23_col0" class="data row23 col0" >0.001%</td>
      <td id="T_3d1c5_row23_col1" class="data row23 col1" >0.001%</td>
      <td id="T_3d1c5_row23_col2" class="data row23 col2" >0.001%</td>
      <td id="T_3d1c5_row23_col3" class="data row23 col3" >0.002%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row24" class="row_heading level0 row24" >L128X256Mix</th>
      <td id="T_3d1c5_row24_col0" class="data row24 col0" >0.000%</td>
      <td id="T_3d1c5_row24_col1" class="data row24 col1" >0.003%</td>
      <td id="T_3d1c5_row24_col2" class="data row24 col2" >0.001%</td>
      <td id="T_3d1c5_row24_col3" class="data row24 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row25" class="row_heading level0 row25" >L128X1024Mix</th>
      <td id="T_3d1c5_row25_col0" class="data row25 col0" >0.001%</td>
      <td id="T_3d1c5_row25_col1" class="data row25 col1" >0.002%</td>
      <td id="T_3d1c5_row25_col2" class="data row25 col2" >0.002%</td>
      <td id="T_3d1c5_row25_col3" class="data row25 col3" >0.003%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row26" class="row_heading level0 row26" >PcgRxsMXs64</th>
      <td id="T_3d1c5_row26_col0" class="data row26 col0" >0.001%</td>
      <td id="T_3d1c5_row26_col1" class="data row26 col1" >0.001%</td>
      <td id="T_3d1c5_row26_col2" class="data row26 col2" >0.001%</td>
      <td id="T_3d1c5_row26_col3" class="data row26 col3" >0.003%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row27" class="row_heading level0 row27" >Philox4x64</th>
      <td id="T_3d1c5_row27_col0" class="data row27 col0" >0.001%</td>
      <td id="T_3d1c5_row27_col1" class="data row27 col1" >0.003%</td>
      <td id="T_3d1c5_row27_col2" class="data row27 col2" >0.001%</td>
      <td id="T_3d1c5_row27_col3" class="data row27 col3" >0.001%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row28" class="row_heading level0 row28" >Drand48</th>
      <td id="T_3d1c5_row28_col0" class="data row28 col0" >0.008%</td>
      <td id="T_3d1c5_row28_col1" class="data row28 col1" >0.003%</td>
      <td id="T_3d1c5_row28_col2" class="data row28 col2" >0.008%</td>
      <td id="T_3d1c5_row28_col3" class="data row28 col3" >0.004%</td>
    </tr>
    <tr>
      <th id="T_3d1c5_level0_row29" class="row_heading level0 row29" >Drand48Mix</th>
      <td id="T_3d1c5_row29_col0" class="data row29 col0" >0.009%</td>
      <td id="T_3d1c5_row29_col1" class="data row29 col1" >0.008%</td>
      <td id="T_3d1c5_row29_col2" class="data row29 col2" >0.005%</td>
      <td id="T_3d1c5_row29_col3" class="data row29 col3" >0.009%</td>
    </tr>
  </tbody>
</table>

### Confidence interval for standard deviation

In [16]:
conf = {}
h_list = []
for rec in data:
    name = rec["name"]
    df = rec["df"]
    for generator in generators:
        l = list(df[df["rng_mode"] == generator]["std"])
        h = mean_confidence_interval(l)[3]  # 95%
        if name not in conf: conf[name] = []
        conf[name].append(h)
        h_list.append(h)

df_conf = pd.DataFrame(conf, index=generators)
df_conf

                   Exponential  Logarithmic     Gamma  Triangular
ThreadLocalRandom     0.005982     0.000951  0.000745    0.000580
Random                0.005652     0.000894  0.000814    0.000659
SecureRandom          0.005372     0.000884  0.000846    0.000538
Well512a              0.005021     0.000865  0.000711    0.000578
Well1024a             0.005557     0.000874  0.000794    0.000527
Well19937a            0.005043     0.000906  0.000806    0.000614
Well19937c            0.006280     0.000841  0.000699    0.000583
Well44497a            0.005831     0.000841  0.000777    0.000572
Well44497b            0.005157     0.000895  0.000788    0.000567
MersenneTwister       0.006024     0.000824  0.000742    0.000523
ISAAC                 0.006105     0.000745  0.000619    0.000631
XoRoShiRo128++        0.005433     0.000868  0.000813    0.000701
XoRoShiRo128**        0.005807     0.000904  0.000806    0.000547
XoRoShiRo64**         0.005504     0.000928  0.000789    0.000587
XoRoShiRo256++        0.005637     0.000781  0.000763    0.000550
XoRoShiRo1024++       0.005681     0.000885  0.000855    0.000579
XoRoShiRo1024*        0.006062     0.000876  0.000832    0.000596
XoRoShiRo1024**       0.004402     0.000922  0.000795    0.000591
L32X64Mix             0.005561     0.000795  0.000728    0.000603
L64X128Mix            0.005839     0.000808  0.000741    0.000529
L64X128**             0.005434     0.000904  0.000724    0.000572
L64X256Mix            0.005513     0.000851  0.000819    0.000621
L64X1024Mix           0.006379     0.000753  0.000755    0.000602
L128X128Mix           0.005473     0.000854  0.000789    0.000547
L128X256Mix           0.006024     0.000777  0.000876    0.000644
L128X1024Mix          0.005779     0.000796  0.000717    0.000573
PcgRxsMXs64           0.005657     0.000755  0.000783    0.000607
Philox4x64            0.005559     0.000851  0.000810    0.000671
Drand48               0.024665     0.003770  0.003128    0.002465
Drand48Mix            0.023000     0.003701  0.003062    0.002479

In [17]:
print(df_conf[(df_conf.index != "Drand48") & (df_conf.index != "Drand48Mix")].max())
print(df_conf[df_conf.index == "Drand48"].max())
print(df_conf[df_conf.index == "Drand48Mix"].max())

Exponential    0.006379
Logarithmic    0.000951
Gamma          0.000876
Triangular     0.000701
dtype: float64
Exponential    0.024665
Logarithmic    0.003770
Gamma          0.003128
Triangular     0.002465
dtype: float64
Exponential    0.023000
Logarithmic    0.003701
Gamma          0.003062
Triangular     0.002479
dtype: float64

## $\Delta^2$

In [18]:
d = {}
for rec in data:
    d[rec["name"]] = rec["delta2"]

df_delta2 = pd.DataFrame(d, index=generators)

df_delta2

                   Exponential  Logarithmic     Gamma  Triangular
ThreadLocalRandom      1.00455      1.00277   0.98729     0.99899
Random                 1.00700      0.99318   0.98839     0.98315
SecureRandom           0.99348      0.99321   1.00888     0.99872
Well512a               0.99287      0.98008   1.00308     0.98627
Well1024a              0.99958      0.98315   1.00869     0.99681
Well19937a             0.99603      1.00379   1.00374     0.98767
Well19937c             1.00755      0.97541   0.99641     0.98882
Well44497a             0.99034      1.00254   0.99169     0.99690
Well44497b             1.00261      1.00373   1.00126     1.01602
MersenneTwister        1.01001      0.99174   0.98136     0.99030
ISAAC                  0.99151      0.97346   0.99425     0.98423
XoRoShiRo128++         1.02216      1.03359   1.03346     1.05463
XoRoShiRo128**         1.03056      1.02448   1.01038     1.00643
XoRoShiRo64**          1.02839      1.02591   1.03440     1.04178
XoRoShiRo256++         1.00447      0.98587   0.99761     0.99858
XoRoShiRo1024++        1.00267      1.00767   1.01301     1.07092
XoRoShiRo1024*         1.02996      1.01117   1.01979     1.06401
XoRoShiRo1024**        1.01952      1.01547   1.02551     1.05635
L32X64Mix              1.03082      1.00588   1.01232     1.01115
L64X128Mix             0.99925      0.99980   0.99630     0.97251
L64X128**              0.99898      1.00217   0.99554     0.99706
L64X256Mix             1.00033      1.00158   0.98481     1.00123
L64X1024Mix            0.98923      0.99999   0.99373     0.99336
L128X128Mix            0.98769      1.00043   0.98558     1.01031
L128X256Mix            0.99065      0.99020   1.00231     0.97990
L128X1024Mix           0.99920      0.98113   0.98865     1.00645
PcgRxsMXs64            1.04505      1.03355   1.03706     1.04303
Philox4x64             1.02172      1.02551   0.99434     1.05822
Drand48               16.56192     18.52441  16.45777    17.56581
Drand48Mix            19.47353     20.13199  20.36621    19.23310

In [19]:
df_delta2[(df_delta2.index != "Drand48") & (df_delta2.index != "Drand48Mix")].max()

Exponential    1.04505
Logarithmic    1.03359
Gamma          1.03706
Triangular     1.07092
dtype: float64

In [20]:
s = df_delta2.style.format("{:.2f}").set_caption("$\\Delta^2$").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{$\Delta^2$}
\begin{tabular}{lrrrr}
 & Exponential & Logarithmic & Gamma & Triangular \\
ThreadLocalRandom & 1.00 & 1.00 & 0.99 & 1.00 \\
Random & 1.01 & 0.99 & 0.99 & 0.98 \\
SecureRandom & 0.99 & 0.99 & 1.01 & 1.00 \\
Well512a & 0.99 & 0.98 & 1.00 & 0.99 \\
Well1024a & 1.00 & 0.98 & 1.01 & 1.00 \\
Well19937a & 1.00 & 1.00 & 1.00 & 0.99 \\
Well19937c & 1.01 & 0.98 & 1.00 & 0.99 \\
Well44497a & 0.99 & 1.00 & 0.99 & 1.00 \\
Well44497b & 1.00 & 1.00 & 1.00 & 1.02 \\
MersenneTwister & 1.01 & 0.99 & 0.98 & 0.99 \\
ISAAC & 0.99 & 0.97 & 0.99 & 0.98 \\
XoRoShiRo128++ & 1.02 & 1.03 & 1.03 & 1.05 \\
XoRoShiRo128** & 1.03 & 1.02 & 1.01 & 1.01 \\
XoRoShiRo64** & 1.03 & 1.03 & 1.03 & 1.04 \\
XoRoShiRo256++ & 1.00 & 0.99 & 1.00 & 1.00 \\
XoRoShiRo1024++ & 1.00 & 1.01 & 1.01 & 1.07 \\
XoRoShiRo1024* & 1.03 & 1.01 & 1.02 & 1.06 \\
XoRoShiRo1024** & 1.02 & 1.02 & 1.03 & 1.06 \\
L32X64Mix & 1.03 & 1.01 & 1.01 & 1.01 \\
L64X128Mix & 1.00 & 1.00 & 1.00 & 0.97 \\
L64X128** & 1.00 & 1.00 & 1.00 & 1.00 \\
L64X256Mix & 1.00 & 1.00 & 0.98 & 1.00 \\
L64X1024Mix & 0.99 & 1.00 & 0.99 & 0.99 \\
L128X128Mix & 0.99 & 1.00 & 0.99 & 1.01 \\
L128X256Mix & 0.99 & 0.99 & 1.00 & 0.98 \\
L128X1024Mix & 1.00 & 0.98 & 0.99 & 1.01 \\
PcgRxsMXs64 & 1.05 & 1.03 & 1.04 & 1.04 \\
Philox4x64 & 1.02 & 1.03 & 0.99 & 1.06 \\
Drand48 & 16.56 & 18.52 & 16.46 & 17.57 \\
Drand48Mix & 19.47 & 20.13 & 20.37 & 19.23 \\
\end{tabular}
\end{table}

In [21]:
s = df_delta2.style.format("{:.2f}").set_caption("&Delta;<sup>2</sup>")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_247ec">
  <caption>&Delta;<sup>2</sup></caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_247ec_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_247ec_level0_col1" class="col_heading level0 col1" >Logarithmic</th>
      <th id="T_247ec_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_247ec_level0_col3" class="col_heading level0 col3" >Triangular</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_247ec_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_247ec_row0_col0" class="data row0 col0" >1.00</td>
      <td id="T_247ec_row0_col1" class="data row0 col1" >1.00</td>
      <td id="T_247ec_row0_col2" class="data row0 col2" >0.99</td>
      <td id="T_247ec_row0_col3" class="data row0 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_247ec_row1_col0" class="data row1 col0" >1.01</td>
      <td id="T_247ec_row1_col1" class="data row1 col1" >0.99</td>
      <td id="T_247ec_row1_col2" class="data row1 col2" >0.99</td>
      <td id="T_247ec_row1_col3" class="data row1 col3" >0.98</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_247ec_row2_col0" class="data row2 col0" >0.99</td>
      <td id="T_247ec_row2_col1" class="data row2 col1" >0.99</td>
      <td id="T_247ec_row2_col2" class="data row2 col2" >1.01</td>
      <td id="T_247ec_row2_col3" class="data row2 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_247ec_row3_col0" class="data row3 col0" >0.99</td>
      <td id="T_247ec_row3_col1" class="data row3 col1" >0.98</td>
      <td id="T_247ec_row3_col2" class="data row3 col2" >1.00</td>
      <td id="T_247ec_row3_col3" class="data row3 col3" >0.99</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_247ec_row4_col0" class="data row4 col0" >1.00</td>
      <td id="T_247ec_row4_col1" class="data row4 col1" >0.98</td>
      <td id="T_247ec_row4_col2" class="data row4 col2" >1.01</td>
      <td id="T_247ec_row4_col3" class="data row4 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_247ec_row5_col0" class="data row5 col0" >1.00</td>
      <td id="T_247ec_row5_col1" class="data row5 col1" >1.00</td>
      <td id="T_247ec_row5_col2" class="data row5 col2" >1.00</td>
      <td id="T_247ec_row5_col3" class="data row5 col3" >0.99</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_247ec_row6_col0" class="data row6 col0" >1.01</td>
      <td id="T_247ec_row6_col1" class="data row6 col1" >0.98</td>
      <td id="T_247ec_row6_col2" class="data row6 col2" >1.00</td>
      <td id="T_247ec_row6_col3" class="data row6 col3" >0.99</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_247ec_row7_col0" class="data row7 col0" >0.99</td>
      <td id="T_247ec_row7_col1" class="data row7 col1" >1.00</td>
      <td id="T_247ec_row7_col2" class="data row7 col2" >0.99</td>
      <td id="T_247ec_row7_col3" class="data row7 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_247ec_row8_col0" class="data row8 col0" >1.00</td>
      <td id="T_247ec_row8_col1" class="data row8 col1" >1.00</td>
      <td id="T_247ec_row8_col2" class="data row8 col2" >1.00</td>
      <td id="T_247ec_row8_col3" class="data row8 col3" >1.02</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_247ec_row9_col0" class="data row9 col0" >1.01</td>
      <td id="T_247ec_row9_col1" class="data row9 col1" >0.99</td>
      <td id="T_247ec_row9_col2" class="data row9 col2" >0.98</td>
      <td id="T_247ec_row9_col3" class="data row9 col3" >0.99</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row10" class="row_heading level0 row10" >ISAAC</th>
      <td id="T_247ec_row10_col0" class="data row10 col0" >0.99</td>
      <td id="T_247ec_row10_col1" class="data row10 col1" >0.97</td>
      <td id="T_247ec_row10_col2" class="data row10 col2" >0.99</td>
      <td id="T_247ec_row10_col3" class="data row10 col3" >0.98</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row11" class="row_heading level0 row11" >XoRoShiRo128++</th>
      <td id="T_247ec_row11_col0" class="data row11 col0" >1.02</td>
      <td id="T_247ec_row11_col1" class="data row11 col1" >1.03</td>
      <td id="T_247ec_row11_col2" class="data row11 col2" >1.03</td>
      <td id="T_247ec_row11_col3" class="data row11 col3" >1.05</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row12" class="row_heading level0 row12" >XoRoShiRo128**</th>
      <td id="T_247ec_row12_col0" class="data row12 col0" >1.03</td>
      <td id="T_247ec_row12_col1" class="data row12 col1" >1.02</td>
      <td id="T_247ec_row12_col2" class="data row12 col2" >1.01</td>
      <td id="T_247ec_row12_col3" class="data row12 col3" >1.01</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row13" class="row_heading level0 row13" >XoRoShiRo64**</th>
      <td id="T_247ec_row13_col0" class="data row13 col0" >1.03</td>
      <td id="T_247ec_row13_col1" class="data row13 col1" >1.03</td>
      <td id="T_247ec_row13_col2" class="data row13 col2" >1.03</td>
      <td id="T_247ec_row13_col3" class="data row13 col3" >1.04</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row14" class="row_heading level0 row14" >XoRoShiRo256++</th>
      <td id="T_247ec_row14_col0" class="data row14 col0" >1.00</td>
      <td id="T_247ec_row14_col1" class="data row14 col1" >0.99</td>
      <td id="T_247ec_row14_col2" class="data row14 col2" >1.00</td>
      <td id="T_247ec_row14_col3" class="data row14 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row15" class="row_heading level0 row15" >XoRoShiRo1024++</th>
      <td id="T_247ec_row15_col0" class="data row15 col0" >1.00</td>
      <td id="T_247ec_row15_col1" class="data row15 col1" >1.01</td>
      <td id="T_247ec_row15_col2" class="data row15 col2" >1.01</td>
      <td id="T_247ec_row15_col3" class="data row15 col3" >1.07</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024*</th>
      <td id="T_247ec_row16_col0" class="data row16 col0" >1.03</td>
      <td id="T_247ec_row16_col1" class="data row16 col1" >1.01</td>
      <td id="T_247ec_row16_col2" class="data row16 col2" >1.02</td>
      <td id="T_247ec_row16_col3" class="data row16 col3" >1.06</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024**</th>
      <td id="T_247ec_row17_col0" class="data row17 col0" >1.02</td>
      <td id="T_247ec_row17_col1" class="data row17 col1" >1.02</td>
      <td id="T_247ec_row17_col2" class="data row17 col2" >1.03</td>
      <td id="T_247ec_row17_col3" class="data row17 col3" >1.06</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row18" class="row_heading level0 row18" >L32X64Mix</th>
      <td id="T_247ec_row18_col0" class="data row18 col0" >1.03</td>
      <td id="T_247ec_row18_col1" class="data row18 col1" >1.01</td>
      <td id="T_247ec_row18_col2" class="data row18 col2" >1.01</td>
      <td id="T_247ec_row18_col3" class="data row18 col3" >1.01</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row19" class="row_heading level0 row19" >L64X128Mix</th>
      <td id="T_247ec_row19_col0" class="data row19 col0" >1.00</td>
      <td id="T_247ec_row19_col1" class="data row19 col1" >1.00</td>
      <td id="T_247ec_row19_col2" class="data row19 col2" >1.00</td>
      <td id="T_247ec_row19_col3" class="data row19 col3" >0.97</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row20" class="row_heading level0 row20" >L64X128**</th>
      <td id="T_247ec_row20_col0" class="data row20 col0" >1.00</td>
      <td id="T_247ec_row20_col1" class="data row20 col1" >1.00</td>
      <td id="T_247ec_row20_col2" class="data row20 col2" >1.00</td>
      <td id="T_247ec_row20_col3" class="data row20 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row21" class="row_heading level0 row21" >L64X256Mix</th>
      <td id="T_247ec_row21_col0" class="data row21 col0" >1.00</td>
      <td id="T_247ec_row21_col1" class="data row21 col1" >1.00</td>
      <td id="T_247ec_row21_col2" class="data row21 col2" >0.98</td>
      <td id="T_247ec_row21_col3" class="data row21 col3" >1.00</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row22" class="row_heading level0 row22" >L64X1024Mix</th>
      <td id="T_247ec_row22_col0" class="data row22 col0" >0.99</td>
      <td id="T_247ec_row22_col1" class="data row22 col1" >1.00</td>
      <td id="T_247ec_row22_col2" class="data row22 col2" >0.99</td>
      <td id="T_247ec_row22_col3" class="data row22 col3" >0.99</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row23" class="row_heading level0 row23" >L128X128Mix</th>
      <td id="T_247ec_row23_col0" class="data row23 col0" >0.99</td>
      <td id="T_247ec_row23_col1" class="data row23 col1" >1.00</td>
      <td id="T_247ec_row23_col2" class="data row23 col2" >0.99</td>
      <td id="T_247ec_row23_col3" class="data row23 col3" >1.01</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row24" class="row_heading level0 row24" >L128X256Mix</th>
      <td id="T_247ec_row24_col0" class="data row24 col0" >0.99</td>
      <td id="T_247ec_row24_col1" class="data row24 col1" >0.99</td>
      <td id="T_247ec_row24_col2" class="data row24 col2" >1.00</td>
      <td id="T_247ec_row24_col3" class="data row24 col3" >0.98</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row25" class="row_heading level0 row25" >L128X1024Mix</th>
      <td id="T_247ec_row25_col0" class="data row25 col0" >1.00</td>
      <td id="T_247ec_row25_col1" class="data row25 col1" >0.98</td>
      <td id="T_247ec_row25_col2" class="data row25 col2" >0.99</td>
      <td id="T_247ec_row25_col3" class="data row25 col3" >1.01</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row26" class="row_heading level0 row26" >PcgRxsMXs64</th>
      <td id="T_247ec_row26_col0" class="data row26 col0" >1.05</td>
      <td id="T_247ec_row26_col1" class="data row26 col1" >1.03</td>
      <td id="T_247ec_row26_col2" class="data row26 col2" >1.04</td>
      <td id="T_247ec_row26_col3" class="data row26 col3" >1.04</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row27" class="row_heading level0 row27" >Philox4x64</th>
      <td id="T_247ec_row27_col0" class="data row27 col0" >1.02</td>
      <td id="T_247ec_row27_col1" class="data row27 col1" >1.03</td>
      <td id="T_247ec_row27_col2" class="data row27 col2" >0.99</td>
      <td id="T_247ec_row27_col3" class="data row27 col3" >1.06</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row28" class="row_heading level0 row28" >Drand48</th>
      <td id="T_247ec_row28_col0" class="data row28 col0" >16.56</td>
      <td id="T_247ec_row28_col1" class="data row28 col1" >18.52</td>
      <td id="T_247ec_row28_col2" class="data row28 col2" >16.46</td>
      <td id="T_247ec_row28_col3" class="data row28 col3" >17.57</td>
    </tr>
    <tr>
      <th id="T_247ec_level0_row29" class="row_heading level0 row29" >Drand48Mix</th>
      <td id="T_247ec_row29_col0" class="data row29 col0" >19.47</td>
      <td id="T_247ec_row29_col1" class="data row29 col1" >20.13</td>
      <td id="T_247ec_row29_col2" class="data row29 col2" >20.37</td>
      <td id="T_247ec_row29_col3" class="data row29 col3" >19.23</td>
    </tr>
  </tbody>
</table>

## Times

In [22]:
generators.append("ThreadLocalRandomSlow")  # Not in quality comparison list since only used for speed comparision

for rec in data:
    df = rec["df"]
    mean = rec["mean"]
    std = rec["std"]

    mean_error = []
    std_error = []
    delta2 = []
    time = []

    for generator in generators:
        mean_error.append(round(abs(df[df["rng_mode"] == generator]["mean"].mean() - mean) / mean * 100, 5))  # Values are in percentage
        std_error.append(round(abs(df[df["rng_mode"] == generator]["std"].mean() - std) / std * 100, 5))  # Values are in percentage
        delta2.append(round(df[df["rng_mode"] == generator]["delta2"].mean() * 100000000, 5))
        time.append(round(df[df["rng_mode"] == generator]["time"].mean(), 5))

    rec["mean_error"] = mean_error
    rec["std_error"] = std_error
    rec["delta2"] = delta2
    rec["time"] = time

In [23]:
average_time = [sum([data[i]["time"][j] for i in range(len(data))]) for j in range(len(generators))]

d = {}
for rec in data:
    d[rec["name"]] = rec["time"]/min(rec["time"])*100

d["Average"] = average_time/np.min(average_time)*100

df_time = pd.DataFrame(d, index=generators)

df_time

,Exponential,Logarithmic,Gamma,Triangular,Average
ThreadLocalRandom,105.331027,100.000000,100.000000,103.340166,100.000000
Random,106.908252,102.005610,103.992306,102.845157,101.760865
SecureRandom,372.178353,411.610636,650.179512,356.196111,440.388423
Well512a,107.321855,108.509391,116.874484,108.822187,108.141232
Well1024a,107.278926,107.099845,117.137136,110.027136,108.141531
Well19937a,108.897429,112.731922,123.060426,112.769392,112.065641
Well19937c,109.979320,112.327217,126.854064,112.561098,113.135400
Well44497a,109.701107,114.114189,124.504813,112.138287,112.811182
Well44497b,111.210224,113.200549,127.405830,112.209240,113.701285
MersenneTwister,107.010208,109.415702,118.882881,107.365792,108.444912
ISAAC,108.221711,107.658452,122.258252,108.986498,109.548668
XoRoShiRo128++,101.580114,106.966300,112.448506,108.608914,105.208119
XoRoShiRo128**,100.120531,104.417962,113.488054,106.499008,103.987019
XoRoShiRo64**,100.113927,107.018822,115.479863,106.214368,105.056678
XoRoShiRo256++,115.226553,120.501118,122.155166,117.592093,116.427026
XoRoShiRo1024++,102.722683,109.334680,106.625933,100.000000,102.525747
XoRoShiRo1024*,106.044308,109.493060,108.478318,100.989187,104.072062
XoRoShiRo1024**,107.010208,109.574083,108.600363,101.796636,104.550013
L32X64Mix,103.359187,105.250172,113.615233,105.795291,104.836047
L64X128Mix,117.735005,122.656966,124.233867,118.110338,118.210024
L64X128**,121.308836,122.160652,125.513158,117.801631,119.200423
L64X256Mix,123.864757,123.163865,126.720961,118.814884,120.611746
L64X1024Mix,125.043238,123.822630,128.084775,119.793698,121.637139
L128X128Mix,122.429528,124.147127,127.971815,121.007361,121.348414
L128X256Mix,121.005445,123.406932,127.645969,121.133499,120.771263
L128X1024Mix,122.458423,124.347037,128.773199,121.187024,121.649801
PcgRxsMXs64,106.274225,110.351735,109.349611,102.054306,104.813714
Philox4x64,108.422321,113.863793,110.762006,104.335577,107.097195
Drand48,100.000000,105.252208,108.904091,103.776669,102.350977
Drand48Mix,108.591148,112.165579,115.536738,111.145366,109.563622
ThreadLocalRandomSlow,111.046764,115.252167,110.897479,107.753749,108.926553

In [24]:

s = df_time.style.format("{:.0f}\\,\\%").set_caption("Times to generate PRN (Normalized to fastest in each column)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Times to generate PRN (Normalized to fastest in each column)}
\begin{tabular}{lrrrrr}
 & Exponential & Logarithmic & Gamma & Triangular & Average \\
ThreadLocalRandom & 105\,\% & 100\,\% & 100\,\% & 103\,\% & 100\,\% \\
Random & 107\,\% & 102\,\% & 104\,\% & 103\,\% & 102\,\% \\
SecureRandom & 372\,\% & 412\,\% & 650\,\% & 356\,\% & 440\,\% \\
Well512a & 107\,\% & 109\,\% & 117\,\% & 109\,\% & 108\,\% \\
Well1024a & 107\,\% & 107\,\% & 117\,\% & 110\,\% & 108\,\% \\
Well19937a & 109\,\% & 113\,\% & 123\,\% & 113\,\% & 112\,\% \\
Well19937c & 110\,\% & 112\,\% & 127\,\% & 113\,\% & 113\,\% \\
Well44497a & 110\,\% & 114\,\% & 125\,\% & 112\,\% & 113\,\% \\
Well44497b & 111\,\% & 113\,\% & 127\,\% & 112\,\% & 114\,\% \\
MersenneTwister & 107\,\% & 109\,\% & 119\,\% & 107\,\% & 108\,\% \\
ISAAC & 108\,\% & 108\,\% & 122\,\% & 109\,\% & 110\,\% \\
XoRoShiRo128++ & 102\,\% & 107\,\% & 112\,\% & 109\,\% & 105\,\% \\
XoRoShiRo128** & 100\,\% & 104\,\% & 113\,\% & 106\,\% & 104\,\% \\
XoRoShiRo64** & 100\,\% & 107\,\% & 115\,\% & 106\,\% & 105\,\% \\
XoRoShiRo256++ & 115\,\% & 121\,\% & 122\,\% & 118\,\% & 116\,\% \\
XoRoShiRo1024++ & 103\,\% & 109\,\% & 107\,\% & 100\,\% & 103\,\% \\
XoRoShiRo1024* & 106\,\% & 109\,\% & 108\,\% & 101\,\% & 104\,\% \\
XoRoShiRo1024** & 107\,\% & 110\,\% & 109\,\% & 102\,\% & 105\,\% \\
L32X64Mix & 103\,\% & 105\,\% & 114\,\% & 106\,\% & 105\,\% \\
L64X128Mix & 118\,\% & 123\,\% & 124\,\% & 118\,\% & 118\,\% \\
L64X128** & 121\,\% & 122\,\% & 126\,\% & 118\,\% & 119\,\% \\
L64X256Mix & 124\,\% & 123\,\% & 127\,\% & 119\,\% & 121\,\% \\
L64X1024Mix & 125\,\% & 124\,\% & 128\,\% & 120\,\% & 122\,\% \\
L128X128Mix & 122\,\% & 124\,\% & 128\,\% & 121\,\% & 121\,\% \\
L128X256Mix & 121\,\% & 123\,\% & 128\,\% & 121\,\% & 121\,\% \\
L128X1024Mix & 122\,\% & 124\,\% & 129\,\% & 121\,\% & 122\,\% \\
PcgRxsMXs64 & 106\,\% & 110\,\% & 109\,\% & 102\,\% & 105\,\% \\
Philox4x64 & 108\,\% & 114\,\% & 111\,\% & 104\,\% & 107\,\% \\
Drand48 & 100\,\% & 105\,\% & 109\,\% & 104\,\% & 102\,\% \\
Drand48Mix & 109\,\% & 112\,\% & 116\,\% & 111\,\% & 110\,\% \\
ThreadLocalRandomSlow & 111\,\% & 115\,\% & 111\,\% & 108\,\% & 109\,\% \\
\end{tabular}
\end{table}

In [25]:

s = df_time.style.format("{:.0f}%").set_caption("Times to generate PRN (Normalized to fastest in each column)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_html())

<style type="text/css">
#T_d9b69 caption {
}
</style>
<table id="T_d9b69">
  <caption>Times to generate PRN (Normalized to fastest in each column)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_d9b69_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_d9b69_level0_col1" class="col_heading level0 col1" >Logarithmic</th>
      <th id="T_d9b69_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_d9b69_level0_col3" class="col_heading level0 col3" >Triangular</th>
      <th id="T_d9b69_level0_col4" class="col_heading level0 col4" >Average</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_d9b69_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_d9b69_row0_col0" class="data row0 col0" >105%</td>
      <td id="T_d9b69_row0_col1" class="data row0 col1" >100%</td>
      <td id="T_d9b69_row0_col2" class="data row0 col2" >100%</td>
      <td id="T_d9b69_row0_col3" class="data row0 col3" >103%</td>
      <td id="T_d9b69_row0_col4" class="data row0 col4" >100%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_d9b69_row1_col0" class="data row1 col0" >107%</td>
      <td id="T_d9b69_row1_col1" class="data row1 col1" >102%</td>
      <td id="T_d9b69_row1_col2" class="data row1 col2" >104%</td>
      <td id="T_d9b69_row1_col3" class="data row1 col3" >103%</td>
      <td id="T_d9b69_row1_col4" class="data row1 col4" >102%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_d9b69_row2_col0" class="data row2 col0" >372%</td>
      <td id="T_d9b69_row2_col1" class="data row2 col1" >412%</td>
      <td id="T_d9b69_row2_col2" class="data row2 col2" >650%</td>
      <td id="T_d9b69_row2_col3" class="data row2 col3" >356%</td>
      <td id="T_d9b69_row2_col4" class="data row2 col4" >440%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_d9b69_row3_col0" class="data row3 col0" >107%</td>
      <td id="T_d9b69_row3_col1" class="data row3 col1" >109%</td>
      <td id="T_d9b69_row3_col2" class="data row3 col2" >117%</td>
      <td id="T_d9b69_row3_col3" class="data row3 col3" >109%</td>
      <td id="T_d9b69_row3_col4" class="data row3 col4" >108%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_d9b69_row4_col0" class="data row4 col0" >107%</td>
      <td id="T_d9b69_row4_col1" class="data row4 col1" >107%</td>
      <td id="T_d9b69_row4_col2" class="data row4 col2" >117%</td>
      <td id="T_d9b69_row4_col3" class="data row4 col3" >110%</td>
      <td id="T_d9b69_row4_col4" class="data row4 col4" >108%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_d9b69_row5_col0" class="data row5 col0" >109%</td>
      <td id="T_d9b69_row5_col1" class="data row5 col1" >113%</td>
      <td id="T_d9b69_row5_col2" class="data row5 col2" >123%</td>
      <td id="T_d9b69_row5_col3" class="data row5 col3" >113%</td>
      <td id="T_d9b69_row5_col4" class="data row5 col4" >112%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_d9b69_row6_col0" class="data row6 col0" >110%</td>
      <td id="T_d9b69_row6_col1" class="data row6 col1" >112%</td>
      <td id="T_d9b69_row6_col2" class="data row6 col2" >127%</td>
      <td id="T_d9b69_row6_col3" class="data row6 col3" >113%</td>
      <td id="T_d9b69_row6_col4" class="data row6 col4" >113%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_d9b69_row7_col0" class="data row7 col0" >110%</td>
      <td id="T_d9b69_row7_col1" class="data row7 col1" >114%</td>
      <td id="T_d9b69_row7_col2" class="data row7 col2" >125%</td>
      <td id="T_d9b69_row7_col3" class="data row7 col3" >112%</td>
      <td id="T_d9b69_row7_col4" class="data row7 col4" >113%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_d9b69_row8_col0" class="data row8 col0" >111%</td>
      <td id="T_d9b69_row8_col1" class="data row8 col1" >113%</td>
      <td id="T_d9b69_row8_col2" class="data row8 col2" >127%</td>
      <td id="T_d9b69_row8_col3" class="data row8 col3" >112%</td>
      <td id="T_d9b69_row8_col4" class="data row8 col4" >114%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_d9b69_row9_col0" class="data row9 col0" >107%</td>
      <td id="T_d9b69_row9_col1" class="data row9 col1" >109%</td>
      <td id="T_d9b69_row9_col2" class="data row9 col2" >119%</td>
      <td id="T_d9b69_row9_col3" class="data row9 col3" >107%</td>
      <td id="T_d9b69_row9_col4" class="data row9 col4" >108%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row10" class="row_heading level0 row10" >ISAAC</th>
      <td id="T_d9b69_row10_col0" class="data row10 col0" >108%</td>
      <td id="T_d9b69_row10_col1" class="data row10 col1" >108%</td>
      <td id="T_d9b69_row10_col2" class="data row10 col2" >122%</td>
      <td id="T_d9b69_row10_col3" class="data row10 col3" >109%</td>
      <td id="T_d9b69_row10_col4" class="data row10 col4" >110%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row11" class="row_heading level0 row11" >XoRoShiRo128++</th>
      <td id="T_d9b69_row11_col0" class="data row11 col0" >102%</td>
      <td id="T_d9b69_row11_col1" class="data row11 col1" >107%</td>
      <td id="T_d9b69_row11_col2" class="data row11 col2" >112%</td>
      <td id="T_d9b69_row11_col3" class="data row11 col3" >109%</td>
      <td id="T_d9b69_row11_col4" class="data row11 col4" >105%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row12" class="row_heading level0 row12" >XoRoShiRo128**</th>
      <td id="T_d9b69_row12_col0" class="data row12 col0" >100%</td>
      <td id="T_d9b69_row12_col1" class="data row12 col1" >104%</td>
      <td id="T_d9b69_row12_col2" class="data row12 col2" >113%</td>
      <td id="T_d9b69_row12_col3" class="data row12 col3" >106%</td>
      <td id="T_d9b69_row12_col4" class="data row12 col4" >104%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row13" class="row_heading level0 row13" >XoRoShiRo64**</th>
      <td id="T_d9b69_row13_col0" class="data row13 col0" >100%</td>
      <td id="T_d9b69_row13_col1" class="data row13 col1" >107%</td>
      <td id="T_d9b69_row13_col2" class="data row13 col2" >115%</td>
      <td id="T_d9b69_row13_col3" class="data row13 col3" >106%</td>
      <td id="T_d9b69_row13_col4" class="data row13 col4" >105%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row14" class="row_heading level0 row14" >XoRoShiRo256++</th>
      <td id="T_d9b69_row14_col0" class="data row14 col0" >115%</td>
      <td id="T_d9b69_row14_col1" class="data row14 col1" >121%</td>
      <td id="T_d9b69_row14_col2" class="data row14 col2" >122%</td>
      <td id="T_d9b69_row14_col3" class="data row14 col3" >118%</td>
      <td id="T_d9b69_row14_col4" class="data row14 col4" >116%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row15" class="row_heading level0 row15" >XoRoShiRo1024++</th>
      <td id="T_d9b69_row15_col0" class="data row15 col0" >103%</td>
      <td id="T_d9b69_row15_col1" class="data row15 col1" >109%</td>
      <td id="T_d9b69_row15_col2" class="data row15 col2" >107%</td>
      <td id="T_d9b69_row15_col3" class="data row15 col3" >100%</td>
      <td id="T_d9b69_row15_col4" class="data row15 col4" >103%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024*</th>
      <td id="T_d9b69_row16_col0" class="data row16 col0" >106%</td>
      <td id="T_d9b69_row16_col1" class="data row16 col1" >109%</td>
      <td id="T_d9b69_row16_col2" class="data row16 col2" >108%</td>
      <td id="T_d9b69_row16_col3" class="data row16 col3" >101%</td>
      <td id="T_d9b69_row16_col4" class="data row16 col4" >104%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024**</th>
      <td id="T_d9b69_row17_col0" class="data row17 col0" >107%</td>
      <td id="T_d9b69_row17_col1" class="data row17 col1" >110%</td>
      <td id="T_d9b69_row17_col2" class="data row17 col2" >109%</td>
      <td id="T_d9b69_row17_col3" class="data row17 col3" >102%</td>
      <td id="T_d9b69_row17_col4" class="data row17 col4" >105%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row18" class="row_heading level0 row18" >L32X64Mix</th>
      <td id="T_d9b69_row18_col0" class="data row18 col0" >103%</td>
      <td id="T_d9b69_row18_col1" class="data row18 col1" >105%</td>
      <td id="T_d9b69_row18_col2" class="data row18 col2" >114%</td>
      <td id="T_d9b69_row18_col3" class="data row18 col3" >106%</td>
      <td id="T_d9b69_row18_col4" class="data row18 col4" >105%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row19" class="row_heading level0 row19" >L64X128Mix</th>
      <td id="T_d9b69_row19_col0" class="data row19 col0" >118%</td>
      <td id="T_d9b69_row19_col1" class="data row19 col1" >123%</td>
      <td id="T_d9b69_row19_col2" class="data row19 col2" >124%</td>
      <td id="T_d9b69_row19_col3" class="data row19 col3" >118%</td>
      <td id="T_d9b69_row19_col4" class="data row19 col4" >118%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row20" class="row_heading level0 row20" >L64X128**</th>
      <td id="T_d9b69_row20_col0" class="data row20 col0" >121%</td>
      <td id="T_d9b69_row20_col1" class="data row20 col1" >122%</td>
      <td id="T_d9b69_row20_col2" class="data row20 col2" >126%</td>
      <td id="T_d9b69_row20_col3" class="data row20 col3" >118%</td>
      <td id="T_d9b69_row20_col4" class="data row20 col4" >119%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row21" class="row_heading level0 row21" >L64X256Mix</th>
      <td id="T_d9b69_row21_col0" class="data row21 col0" >124%</td>
      <td id="T_d9b69_row21_col1" class="data row21 col1" >123%</td>
      <td id="T_d9b69_row21_col2" class="data row21 col2" >127%</td>
      <td id="T_d9b69_row21_col3" class="data row21 col3" >119%</td>
      <td id="T_d9b69_row21_col4" class="data row21 col4" >121%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row22" class="row_heading level0 row22" >L64X1024Mix</th>
      <td id="T_d9b69_row22_col0" class="data row22 col0" >125%</td>
      <td id="T_d9b69_row22_col1" class="data row22 col1" >124%</td>
      <td id="T_d9b69_row22_col2" class="data row22 col2" >128%</td>
      <td id="T_d9b69_row22_col3" class="data row22 col3" >120%</td>
      <td id="T_d9b69_row22_col4" class="data row22 col4" >122%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row23" class="row_heading level0 row23" >L128X128Mix</th>
      <td id="T_d9b69_row23_col0" class="data row23 col0" >122%</td>
      <td id="T_d9b69_row23_col1" class="data row23 col1" >124%</td>
      <td id="T_d9b69_row23_col2" class="data row23 col2" >128%</td>
      <td id="T_d9b69_row23_col3" class="data row23 col3" >121%</td>
      <td id="T_d9b69_row23_col4" class="data row23 col4" >121%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row24" class="row_heading level0 row24" >L128X256Mix</th>
      <td id="T_d9b69_row24_col0" class="data row24 col0" >121%</td>
      <td id="T_d9b69_row24_col1" class="data row24 col1" >123%</td>
      <td id="T_d9b69_row24_col2" class="data row24 col2" >128%</td>
      <td id="T_d9b69_row24_col3" class="data row24 col3" >121%</td>
      <td id="T_d9b69_row24_col4" class="data row24 col4" >121%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row25" class="row_heading level0 row25" >L128X1024Mix</th>
      <td id="T_d9b69_row25_col0" class="data row25 col0" >122%</td>
      <td id="T_d9b69_row25_col1" class="data row25 col1" >124%</td>
      <td id="T_d9b69_row25_col2" class="data row25 col2" >129%</td>
      <td id="T_d9b69_row25_col3" class="data row25 col3" >121%</td>
      <td id="T_d9b69_row25_col4" class="data row25 col4" >122%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row26" class="row_heading level0 row26" >PcgRxsMXs64</th>
      <td id="T_d9b69_row26_col0" class="data row26 col0" >106%</td>
      <td id="T_d9b69_row26_col1" class="data row26 col1" >110%</td>
      <td id="T_d9b69_row26_col2" class="data row26 col2" >109%</td>
      <td id="T_d9b69_row26_col3" class="data row26 col3" >102%</td>
      <td id="T_d9b69_row26_col4" class="data row26 col4" >105%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row27" class="row_heading level0 row27" >Philox4x64</th>
      <td id="T_d9b69_row27_col0" class="data row27 col0" >108%</td>
      <td id="T_d9b69_row27_col1" class="data row27 col1" >114%</td>
      <td id="T_d9b69_row27_col2" class="data row27 col2" >111%</td>
      <td id="T_d9b69_row27_col3" class="data row27 col3" >104%</td>
      <td id="T_d9b69_row27_col4" class="data row27 col4" >107%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row28" class="row_heading level0 row28" >Drand48</th>
      <td id="T_d9b69_row28_col0" class="data row28 col0" >100%</td>
      <td id="T_d9b69_row28_col1" class="data row28 col1" >105%</td>
      <td id="T_d9b69_row28_col2" class="data row28 col2" >109%</td>
      <td id="T_d9b69_row28_col3" class="data row28 col3" >104%</td>
      <td id="T_d9b69_row28_col4" class="data row28 col4" >102%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row29" class="row_heading level0 row29" >Drand48Mix</th>
      <td id="T_d9b69_row29_col0" class="data row29 col0" >109%</td>
      <td id="T_d9b69_row29_col1" class="data row29 col1" >112%</td>
      <td id="T_d9b69_row29_col2" class="data row29 col2" >116%</td>
      <td id="T_d9b69_row29_col3" class="data row29 col3" >111%</td>
      <td id="T_d9b69_row29_col4" class="data row29 col4" >110%</td>
    </tr>
    <tr>
      <th id="T_d9b69_level0_row30" class="row_heading level0 row30" >ThreadLocalRandomSlow</th>
      <td id="T_d9b69_row30_col0" class="data row30 col0" >111%</td>
      <td id="T_d9b69_row30_col1" class="data row30 col1" >115%</td>
      <td id="T_d9b69_row30_col2" class="data row30 col2" >111%</td>
      <td id="T_d9b69_row30_col3" class="data row30 col3" >108%</td>
      <td id="T_d9b69_row30_col4" class="data row30 col4" >109%</td>
    </tr>
  </tbody>
</table>