# Comparision of different PRNGs (Model 1)

The Python code in this notebook will load the simulation results stored in the `statistics` folder and will generate the tables for model 1 shown in the report.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), stats.sem(a)
    h = se * stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h, h

## Load and process data

In [3]:
data = [
    {"name": "Exponential", "file": "statistics/results1Exp.txt", "mean": 200, "std": 200},
    {"name": "Log-Normal", "file": "statistics/results1Log.txt", "mean": 200, "std": 50},
    {"name": "Gamma", "file": "statistics/results1Gamma.txt", "mean": 200, "std": 50},
    {"name": "Triangular", "file": "statistics/results1Triangular.txt", "mean": 200, "std": 50},
    {"name": "Poisson", "file": "statistics/results1Poisson.txt", "mean": 200, "std": np.sqrt(200)},
    {"name": "Geometric", "file": "statistics/results1Geometric.txt", "mean": 200, "std": np.sqrt(201 * 200)}
]

In [4]:
for i in range(len(data)):
    data[i]["df"] = pd.read_csv(data[i]["file"], header=None, names=["rng_mode", "n", "mean", "std", "delta2", "time"], sep="\t")

In [5]:
generators=data[0]["df"]["rng_mode"].drop_duplicates().tolist()
generators.remove("ThreadLocalRandomSlow")  # This is the same a "ThreadLocalRandom". Only used for speed comparision. Removed from other tables.

In [6]:
for rec in data:
    df = rec["df"]
    mean = rec["mean"]
    std = rec["std"]

    mean_error = []
    std_error = []
    delta2 = []
    time = []

    for generator in generators:
        mean_error.append(round(abs(df[df["rng_mode"] == generator]["mean"].mean() - mean) / mean * 100, 5))  # Values are in percentage
        std_error.append(round(abs(df[df["rng_mode"] == generator]["std"].mean() - std) / std * 100, 5))  # Values are in percentage
        delta2.append(round(df[df["rng_mode"] == generator]["delta2"].mean() * 100000000, 5))
        time.append(round(df[df["rng_mode"] == generator]["time"].mean(), 5))

    rec["mean_error"] = mean_error
    rec["std_error"] = std_error
    rec["delta2"] = delta2
    rec["time"] = time

## Mean (not used in the report)

In [7]:
d = {}
for rec in data:
    d[rec["name"]] = rec["mean_error"]

df_mean = pd.DataFrame(d, index=generators)

df_mean

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric
ThreadLocalRandom,0.00009,0.00049,0.00013,0.00003,0.00006,0.00154
Random,0.00170,0.00012,0.00100,0.00015,0.00001,0.00159
SecureRandom,0.00055,0.00065,0.00010,0.00014,0.00014,0.00164
Well512a,0.00099,0.00021,0.00021,0.00028,0.00003,0.00042
Well1024a,0.00100,0.00010,0.00038,0.00017,0.00001,0.00025
Well19937a,0.00056,0.00063,0.00009,0.00050,0.00006,0.00001
Well19937c,0.00101,0.00022,0.00009,0.00041,0.00002,0.00010
Well44497a,0.00056,0.00018,0.00080,0.00008,0.00011,0.00045
Well44497b,0.00049,0.00029,0.00019,0.00088,0.00006,0.00004
MersenneTwister,0.00014,0.00031,0.00066,0.00023,0.00002,0.00104
SFC64,0.00159,0.00024,0.00041,0.00042,0.00004,0.00095
ISAAC,0.00008,0.00021,0.00024,0.00027,0.00004,0.00054
XoRoShiRo128++,0.00062,0.00005,0.00048,0.00001,0.00007,0.00115
XoRoShiRo128**,0.00109,0.00025,0.00078,0.00018,0.00014,0.00049
XoRoShiRo64**,0.00022,0.00002,0.00003,0.00038,0.00001,0.00108
XoRoShiRo256++,0.00063,0.00003,0.00025,0.00052,0.00001,0.00127
XoRoShiRo1024++,0.00006,0.00041,0.00050,0.00032,0.00003,0.00227
XoRoShiRo1024*,0.00061,0.00034,0.00002,0.00043,0.00004,0.00088
XoRoShiRo1024**,0.00049,0.00045,0.00016,0.00029,0.00003,0.00247
L32X64Mix,0.00125,0.00041,0.00004,0.00075,0.00004,0.00043
L64X128Mix,0.00043,0.00022,0.00024,0.00007,0.00003,0.00135
L64X128**,0.00174,0.00004,0.00035,0.00027,0.00003,0.00085
L64X256Mix,0.00111,0.00041,0.00011,0.00044,0.00008,0.00065
L64X1024Mix,0.00227,0.00050,0.00052,0.00015,0.00000,0.00053
L128X128Mix,0.00176,0.00004,0.00021,0.00027,0.00001,0.00031
L128X256Mix,0.00001,0.00047,0.00016,0.00018,0.00006,0.00007
L128X1024Mix,0.00015,0.00001,0.00030,0.00002,0.00005,0.00047
PcgRxsMXs64,0.00156,0.00055,0.00033,0.00030,0.00003,0.00124
Philox4x64,0.00057,0.00007,0.00010,0.00012,0.00007,0.00016
Drand48,0.00060,0.00027,0.00134,0.00046,0.00029,0.00518
Drand48Mix,0.00388,0.00033,0.00065,0.00123,0.00006,0.00344

In [8]:

s = df_mean.style.format("{:.5f}\\,\\%").set_caption("Mean Error (in \\%)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Mean Error (in \%)}
\begin{tabular}{lrrrrrr}
 & Exponential & Log-Normal & Gamma & Triangular & Poisson & Geometric \\
ThreadLocalRandom & 0.00009\,\% & 0.00049\,\% & 0.00013\,\% & 0.00003\,\% & 0.00006\,\% & 0.00154\,\% \\
Random & 0.00170\,\% & 0.00012\,\% & 0.00100\,\% & 0.00015\,\% & 0.00001\,\% & 0.00159\,\% \\
SecureRandom & 0.00055\,\% & 0.00065\,\% & 0.00010\,\% & 0.00014\,\% & 0.00014\,\% & 0.00164\,\% \\
Well512a & 0.00099\,\% & 0.00021\,\% & 0.00021\,\% & 0.00028\,\% & 0.00003\,\% & 0.00042\,\% \\
Well1024a & 0.00100\,\% & 0.00010\,\% & 0.00038\,\% & 0.00017\,\% & 0.00001\,\% & 0.00025\,\% \\
Well19937a & 0.00056\,\% & 0.00063\,\% & 0.00009\,\% & 0.00050\,\% & 0.00006\,\% & 0.00001\,\% \\
Well19937c & 0.00101\,\% & 0.00022\,\% & 0.00009\,\% & 0.00041\,\% & 0.00002\,\% & 0.00010\,\% \\
Well44497a & 0.00056\,\% & 0.00018\,\% & 0.00080\,\% & 0.00008\,\% & 0.00011\,\% & 0.00045\,\% \\
Well44497b & 0.00049\,\% & 0.00029\,\% & 0.00019\,\% & 0.00088\,\% & 0.00006\,\% & 0.00004\,\% \\
MersenneTwister & 0.00014\,\% & 0.00031\,\% & 0.00066\,\% & 0.00023\,\% & 0.00002\,\% & 0.00104\,\% \\
SFC64 & 0.00159\,\% & 0.00024\,\% & 0.00041\,\% & 0.00042\,\% & 0.00004\,\% & 0.00095\,\% \\
ISAAC & 0.00008\,\% & 0.00021\,\% & 0.00024\,\% & 0.00027\,\% & 0.00004\,\% & 0.00054\,\% \\
XoRoShiRo128++ & 0.00062\,\% & 0.00005\,\% & 0.00048\,\% & 0.00001\,\% & 0.00007\,\% & 0.00115\,\% \\
XoRoShiRo128** & 0.00109\,\% & 0.00025\,\% & 0.00078\,\% & 0.00018\,\% & 0.00014\,\% & 0.00049\,\% \\
XoRoShiRo64** & 0.00022\,\% & 0.00002\,\% & 0.00003\,\% & 0.00038\,\% & 0.00001\,\% & 0.00108\,\% \\
XoRoShiRo256++ & 0.00063\,\% & 0.00003\,\% & 0.00025\,\% & 0.00052\,\% & 0.00001\,\% & 0.00127\,\% \\
XoRoShiRo1024++ & 0.00006\,\% & 0.00041\,\% & 0.00050\,\% & 0.00032\,\% & 0.00003\,\% & 0.00227\,\% \\
XoRoShiRo1024* & 0.00061\,\% & 0.00034\,\% & 0.00002\,\% & 0.00043\,\% & 0.00004\,\% & 0.00088\,\% \\
XoRoShiRo1024** & 0.00049\,\% & 0.00045\,\% & 0.00016\,\% & 0.00029\,\% & 0.00003\,\% & 0.00247\,\% \\
L32X64Mix & 0.00125\,\% & 0.00041\,\% & 0.00004\,\% & 0.00075\,\% & 0.00004\,\% & 0.00043\,\% \\
L64X128Mix & 0.00043\,\% & 0.00022\,\% & 0.00024\,\% & 0.00007\,\% & 0.00003\,\% & 0.00135\,\% \\
L64X128** & 0.00174\,\% & 0.00004\,\% & 0.00035\,\% & 0.00027\,\% & 0.00003\,\% & 0.00085\,\% \\
L64X256Mix & 0.00111\,\% & 0.00041\,\% & 0.00011\,\% & 0.00044\,\% & 0.00008\,\% & 0.00065\,\% \\
L64X1024Mix & 0.00227\,\% & 0.00050\,\% & 0.00052\,\% & 0.00015\,\% & 0.00000\,\% & 0.00053\,\% \\
L128X128Mix & 0.00176\,\% & 0.00004\,\% & 0.00021\,\% & 0.00027\,\% & 0.00001\,\% & 0.00031\,\% \\
L128X256Mix & 0.00001\,\% & 0.00047\,\% & 0.00016\,\% & 0.00018\,\% & 0.00006\,\% & 0.00007\,\% \\
L128X1024Mix & 0.00015\,\% & 0.00001\,\% & 0.00030\,\% & 0.00002\,\% & 0.00005\,\% & 0.00047\,\% \\
PcgRxsMXs64 & 0.00156\,\% & 0.00055\,\% & 0.00033\,\% & 0.00030\,\% & 0.00003\,\% & 0.00124\,\% \\
Philox4x64 & 0.00057\,\% & 0.00007\,\% & 0.00010\,\% & 0.00012\,\% & 0.00007\,\% & 0.00016\,\% \\
Drand48 & 0.00060\,\% & 0.00027\,\% & 0.00134\,\% & 0.00046\,\% & 0.00029\,\% & 0.00518\,\% \\
Drand48Mix & 0.00388\,\% & 0.00033\,\% & 0.00065\,\% & 0.00123\,\% & 0.00006\,\% & 0.00344\,\% \\
\end{tabular}
\end{table}

In [9]:
s = df_mean.style.format("{:.5f}%").set_caption("Mean Error (in %)")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_42c7e">
  <caption>Mean Error (in %)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_42c7e_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_42c7e_level0_col1" class="col_heading level0 col1" >Log-Normal</th>
      <th id="T_42c7e_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_42c7e_level0_col3" class="col_heading level0 col3" >Triangular</th>
      <th id="T_42c7e_level0_col4" class="col_heading level0 col4" >Poisson</th>
      <th id="T_42c7e_level0_col5" class="col_heading level0 col5" >Geometric</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_42c7e_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_42c7e_row0_col0" class="data row0 col0" >0.00009%</td>
      <td id="T_42c7e_row0_col1" class="data row0 col1" >0.00049%</td>
      <td id="T_42c7e_row0_col2" class="data row0 col2" >0.00013%</td>
      <td id="T_42c7e_row0_col3" class="data row0 col3" >0.00003%</td>
      <td id="T_42c7e_row0_col4" class="data row0 col4" >0.00006%</td>
      <td id="T_42c7e_row0_col5" class="data row0 col5" >0.00154%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_42c7e_row1_col0" class="data row1 col0" >0.00170%</td>
      <td id="T_42c7e_row1_col1" class="data row1 col1" >0.00012%</td>
      <td id="T_42c7e_row1_col2" class="data row1 col2" >0.00100%</td>
      <td id="T_42c7e_row1_col3" class="data row1 col3" >0.00015%</td>
      <td id="T_42c7e_row1_col4" class="data row1 col4" >0.00001%</td>
      <td id="T_42c7e_row1_col5" class="data row1 col5" >0.00159%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_42c7e_row2_col0" class="data row2 col0" >0.00055%</td>
      <td id="T_42c7e_row2_col1" class="data row2 col1" >0.00065%</td>
      <td id="T_42c7e_row2_col2" class="data row2 col2" >0.00010%</td>
      <td id="T_42c7e_row2_col3" class="data row2 col3" >0.00014%</td>
      <td id="T_42c7e_row2_col4" class="data row2 col4" >0.00014%</td>
      <td id="T_42c7e_row2_col5" class="data row2 col5" >0.00164%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_42c7e_row3_col0" class="data row3 col0" >0.00099%</td>
      <td id="T_42c7e_row3_col1" class="data row3 col1" >0.00021%</td>
      <td id="T_42c7e_row3_col2" class="data row3 col2" >0.00021%</td>
      <td id="T_42c7e_row3_col3" class="data row3 col3" >0.00028%</td>
      <td id="T_42c7e_row3_col4" class="data row3 col4" >0.00003%</td>
      <td id="T_42c7e_row3_col5" class="data row3 col5" >0.00042%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_42c7e_row4_col0" class="data row4 col0" >0.00100%</td>
      <td id="T_42c7e_row4_col1" class="data row4 col1" >0.00010%</td>
      <td id="T_42c7e_row4_col2" class="data row4 col2" >0.00038%</td>
      <td id="T_42c7e_row4_col3" class="data row4 col3" >0.00017%</td>
      <td id="T_42c7e_row4_col4" class="data row4 col4" >0.00001%</td>
      <td id="T_42c7e_row4_col5" class="data row4 col5" >0.00025%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_42c7e_row5_col0" class="data row5 col0" >0.00056%</td>
      <td id="T_42c7e_row5_col1" class="data row5 col1" >0.00063%</td>
      <td id="T_42c7e_row5_col2" class="data row5 col2" >0.00009%</td>
      <td id="T_42c7e_row5_col3" class="data row5 col3" >0.00050%</td>
      <td id="T_42c7e_row5_col4" class="data row5 col4" >0.00006%</td>
      <td id="T_42c7e_row5_col5" class="data row5 col5" >0.00001%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_42c7e_row6_col0" class="data row6 col0" >0.00101%</td>
      <td id="T_42c7e_row6_col1" class="data row6 col1" >0.00022%</td>
      <td id="T_42c7e_row6_col2" class="data row6 col2" >0.00009%</td>
      <td id="T_42c7e_row6_col3" class="data row6 col3" >0.00041%</td>
      <td id="T_42c7e_row6_col4" class="data row6 col4" >0.00002%</td>
      <td id="T_42c7e_row6_col5" class="data row6 col5" >0.00010%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_42c7e_row7_col0" class="data row7 col0" >0.00056%</td>
      <td id="T_42c7e_row7_col1" class="data row7 col1" >0.00018%</td>
      <td id="T_42c7e_row7_col2" class="data row7 col2" >0.00080%</td>
      <td id="T_42c7e_row7_col3" class="data row7 col3" >0.00008%</td>
      <td id="T_42c7e_row7_col4" class="data row7 col4" >0.00011%</td>
      <td id="T_42c7e_row7_col5" class="data row7 col5" >0.00045%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_42c7e_row8_col0" class="data row8 col0" >0.00049%</td>
      <td id="T_42c7e_row8_col1" class="data row8 col1" >0.00029%</td>
      <td id="T_42c7e_row8_col2" class="data row8 col2" >0.00019%</td>
      <td id="T_42c7e_row8_col3" class="data row8 col3" >0.00088%</td>
      <td id="T_42c7e_row8_col4" class="data row8 col4" >0.00006%</td>
      <td id="T_42c7e_row8_col5" class="data row8 col5" >0.00004%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_42c7e_row9_col0" class="data row9 col0" >0.00014%</td>
      <td id="T_42c7e_row9_col1" class="data row9 col1" >0.00031%</td>
      <td id="T_42c7e_row9_col2" class="data row9 col2" >0.00066%</td>
      <td id="T_42c7e_row9_col3" class="data row9 col3" >0.00023%</td>
      <td id="T_42c7e_row9_col4" class="data row9 col4" >0.00002%</td>
      <td id="T_42c7e_row9_col5" class="data row9 col5" >0.00104%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row10" class="row_heading level0 row10" >SFC64</th>
      <td id="T_42c7e_row10_col0" class="data row10 col0" >0.00159%</td>
      <td id="T_42c7e_row10_col1" class="data row10 col1" >0.00024%</td>
      <td id="T_42c7e_row10_col2" class="data row10 col2" >0.00041%</td>
      <td id="T_42c7e_row10_col3" class="data row10 col3" >0.00042%</td>
      <td id="T_42c7e_row10_col4" class="data row10 col4" >0.00004%</td>
      <td id="T_42c7e_row10_col5" class="data row10 col5" >0.00095%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row11" class="row_heading level0 row11" >ISAAC</th>
      <td id="T_42c7e_row11_col0" class="data row11 col0" >0.00008%</td>
      <td id="T_42c7e_row11_col1" class="data row11 col1" >0.00021%</td>
      <td id="T_42c7e_row11_col2" class="data row11 col2" >0.00024%</td>
      <td id="T_42c7e_row11_col3" class="data row11 col3" >0.00027%</td>
      <td id="T_42c7e_row11_col4" class="data row11 col4" >0.00004%</td>
      <td id="T_42c7e_row11_col5" class="data row11 col5" >0.00054%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row12" class="row_heading level0 row12" >XoRoShiRo128++</th>
      <td id="T_42c7e_row12_col0" class="data row12 col0" >0.00062%</td>
      <td id="T_42c7e_row12_col1" class="data row12 col1" >0.00005%</td>
      <td id="T_42c7e_row12_col2" class="data row12 col2" >0.00048%</td>
      <td id="T_42c7e_row12_col3" class="data row12 col3" >0.00001%</td>
      <td id="T_42c7e_row12_col4" class="data row12 col4" >0.00007%</td>
      <td id="T_42c7e_row12_col5" class="data row12 col5" >0.00115%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row13" class="row_heading level0 row13" >XoRoShiRo128**</th>
      <td id="T_42c7e_row13_col0" class="data row13 col0" >0.00109%</td>
      <td id="T_42c7e_row13_col1" class="data row13 col1" >0.00025%</td>
      <td id="T_42c7e_row13_col2" class="data row13 col2" >0.00078%</td>
      <td id="T_42c7e_row13_col3" class="data row13 col3" >0.00018%</td>
      <td id="T_42c7e_row13_col4" class="data row13 col4" >0.00014%</td>
      <td id="T_42c7e_row13_col5" class="data row13 col5" >0.00049%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row14" class="row_heading level0 row14" >XoRoShiRo64**</th>
      <td id="T_42c7e_row14_col0" class="data row14 col0" >0.00022%</td>
      <td id="T_42c7e_row14_col1" class="data row14 col1" >0.00002%</td>
      <td id="T_42c7e_row14_col2" class="data row14 col2" >0.00003%</td>
      <td id="T_42c7e_row14_col3" class="data row14 col3" >0.00038%</td>
      <td id="T_42c7e_row14_col4" class="data row14 col4" >0.00001%</td>
      <td id="T_42c7e_row14_col5" class="data row14 col5" >0.00108%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row15" class="row_heading level0 row15" >XoRoShiRo256++</th>
      <td id="T_42c7e_row15_col0" class="data row15 col0" >0.00063%</td>
      <td id="T_42c7e_row15_col1" class="data row15 col1" >0.00003%</td>
      <td id="T_42c7e_row15_col2" class="data row15 col2" >0.00025%</td>
      <td id="T_42c7e_row15_col3" class="data row15 col3" >0.00052%</td>
      <td id="T_42c7e_row15_col4" class="data row15 col4" >0.00001%</td>
      <td id="T_42c7e_row15_col5" class="data row15 col5" >0.00127%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024++</th>
      <td id="T_42c7e_row16_col0" class="data row16 col0" >0.00006%</td>
      <td id="T_42c7e_row16_col1" class="data row16 col1" >0.00041%</td>
      <td id="T_42c7e_row16_col2" class="data row16 col2" >0.00050%</td>
      <td id="T_42c7e_row16_col3" class="data row16 col3" >0.00032%</td>
      <td id="T_42c7e_row16_col4" class="data row16 col4" >0.00003%</td>
      <td id="T_42c7e_row16_col5" class="data row16 col5" >0.00227%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024*</th>
      <td id="T_42c7e_row17_col0" class="data row17 col0" >0.00061%</td>
      <td id="T_42c7e_row17_col1" class="data row17 col1" >0.00034%</td>
      <td id="T_42c7e_row17_col2" class="data row17 col2" >0.00002%</td>
      <td id="T_42c7e_row17_col3" class="data row17 col3" >0.00043%</td>
      <td id="T_42c7e_row17_col4" class="data row17 col4" >0.00004%</td>
      <td id="T_42c7e_row17_col5" class="data row17 col5" >0.00088%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row18" class="row_heading level0 row18" >XoRoShiRo1024**</th>
      <td id="T_42c7e_row18_col0" class="data row18 col0" >0.00049%</td>
      <td id="T_42c7e_row18_col1" class="data row18 col1" >0.00045%</td>
      <td id="T_42c7e_row18_col2" class="data row18 col2" >0.00016%</td>
      <td id="T_42c7e_row18_col3" class="data row18 col3" >0.00029%</td>
      <td id="T_42c7e_row18_col4" class="data row18 col4" >0.00003%</td>
      <td id="T_42c7e_row18_col5" class="data row18 col5" >0.00247%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row19" class="row_heading level0 row19" >L32X64Mix</th>
      <td id="T_42c7e_row19_col0" class="data row19 col0" >0.00125%</td>
      <td id="T_42c7e_row19_col1" class="data row19 col1" >0.00041%</td>
      <td id="T_42c7e_row19_col2" class="data row19 col2" >0.00004%</td>
      <td id="T_42c7e_row19_col3" class="data row19 col3" >0.00075%</td>
      <td id="T_42c7e_row19_col4" class="data row19 col4" >0.00004%</td>
      <td id="T_42c7e_row19_col5" class="data row19 col5" >0.00043%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row20" class="row_heading level0 row20" >L64X128Mix</th>
      <td id="T_42c7e_row20_col0" class="data row20 col0" >0.00043%</td>
      <td id="T_42c7e_row20_col1" class="data row20 col1" >0.00022%</td>
      <td id="T_42c7e_row20_col2" class="data row20 col2" >0.00024%</td>
      <td id="T_42c7e_row20_col3" class="data row20 col3" >0.00007%</td>
      <td id="T_42c7e_row20_col4" class="data row20 col4" >0.00003%</td>
      <td id="T_42c7e_row20_col5" class="data row20 col5" >0.00135%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row21" class="row_heading level0 row21" >L64X128**</th>
      <td id="T_42c7e_row21_col0" class="data row21 col0" >0.00174%</td>
      <td id="T_42c7e_row21_col1" class="data row21 col1" >0.00004%</td>
      <td id="T_42c7e_row21_col2" class="data row21 col2" >0.00035%</td>
      <td id="T_42c7e_row21_col3" class="data row21 col3" >0.00027%</td>
      <td id="T_42c7e_row21_col4" class="data row21 col4" >0.00003%</td>
      <td id="T_42c7e_row21_col5" class="data row21 col5" >0.00085%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row22" class="row_heading level0 row22" >L64X256Mix</th>
      <td id="T_42c7e_row22_col0" class="data row22 col0" >0.00111%</td>
      <td id="T_42c7e_row22_col1" class="data row22 col1" >0.00041%</td>
      <td id="T_42c7e_row22_col2" class="data row22 col2" >0.00011%</td>
      <td id="T_42c7e_row22_col3" class="data row22 col3" >0.00044%</td>
      <td id="T_42c7e_row22_col4" class="data row22 col4" >0.00008%</td>
      <td id="T_42c7e_row22_col5" class="data row22 col5" >0.00065%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row23" class="row_heading level0 row23" >L64X1024Mix</th>
      <td id="T_42c7e_row23_col0" class="data row23 col0" >0.00227%</td>
      <td id="T_42c7e_row23_col1" class="data row23 col1" >0.00050%</td>
      <td id="T_42c7e_row23_col2" class="data row23 col2" >0.00052%</td>
      <td id="T_42c7e_row23_col3" class="data row23 col3" >0.00015%</td>
      <td id="T_42c7e_row23_col4" class="data row23 col4" >0.00000%</td>
      <td id="T_42c7e_row23_col5" class="data row23 col5" >0.00053%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row24" class="row_heading level0 row24" >L128X128Mix</th>
      <td id="T_42c7e_row24_col0" class="data row24 col0" >0.00176%</td>
      <td id="T_42c7e_row24_col1" class="data row24 col1" >0.00004%</td>
      <td id="T_42c7e_row24_col2" class="data row24 col2" >0.00021%</td>
      <td id="T_42c7e_row24_col3" class="data row24 col3" >0.00027%</td>
      <td id="T_42c7e_row24_col4" class="data row24 col4" >0.00001%</td>
      <td id="T_42c7e_row24_col5" class="data row24 col5" >0.00031%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row25" class="row_heading level0 row25" >L128X256Mix</th>
      <td id="T_42c7e_row25_col0" class="data row25 col0" >0.00001%</td>
      <td id="T_42c7e_row25_col1" class="data row25 col1" >0.00047%</td>
      <td id="T_42c7e_row25_col2" class="data row25 col2" >0.00016%</td>
      <td id="T_42c7e_row25_col3" class="data row25 col3" >0.00018%</td>
      <td id="T_42c7e_row25_col4" class="data row25 col4" >0.00006%</td>
      <td id="T_42c7e_row25_col5" class="data row25 col5" >0.00007%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row26" class="row_heading level0 row26" >L128X1024Mix</th>
      <td id="T_42c7e_row26_col0" class="data row26 col0" >0.00015%</td>
      <td id="T_42c7e_row26_col1" class="data row26 col1" >0.00001%</td>
      <td id="T_42c7e_row26_col2" class="data row26 col2" >0.00030%</td>
      <td id="T_42c7e_row26_col3" class="data row26 col3" >0.00002%</td>
      <td id="T_42c7e_row26_col4" class="data row26 col4" >0.00005%</td>
      <td id="T_42c7e_row26_col5" class="data row26 col5" >0.00047%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row27" class="row_heading level0 row27" >PcgRxsMXs64</th>
      <td id="T_42c7e_row27_col0" class="data row27 col0" >0.00156%</td>
      <td id="T_42c7e_row27_col1" class="data row27 col1" >0.00055%</td>
      <td id="T_42c7e_row27_col2" class="data row27 col2" >0.00033%</td>
      <td id="T_42c7e_row27_col3" class="data row27 col3" >0.00030%</td>
      <td id="T_42c7e_row27_col4" class="data row27 col4" >0.00003%</td>
      <td id="T_42c7e_row27_col5" class="data row27 col5" >0.00124%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row28" class="row_heading level0 row28" >Philox4x64</th>
      <td id="T_42c7e_row28_col0" class="data row28 col0" >0.00057%</td>
      <td id="T_42c7e_row28_col1" class="data row28 col1" >0.00007%</td>
      <td id="T_42c7e_row28_col2" class="data row28 col2" >0.00010%</td>
      <td id="T_42c7e_row28_col3" class="data row28 col3" >0.00012%</td>
      <td id="T_42c7e_row28_col4" class="data row28 col4" >0.00007%</td>
      <td id="T_42c7e_row28_col5" class="data row28 col5" >0.00016%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row29" class="row_heading level0 row29" >Drand48</th>
      <td id="T_42c7e_row29_col0" class="data row29 col0" >0.00060%</td>
      <td id="T_42c7e_row29_col1" class="data row29 col1" >0.00027%</td>
      <td id="T_42c7e_row29_col2" class="data row29 col2" >0.00134%</td>
      <td id="T_42c7e_row29_col3" class="data row29 col3" >0.00046%</td>
      <td id="T_42c7e_row29_col4" class="data row29 col4" >0.00029%</td>
      <td id="T_42c7e_row29_col5" class="data row29 col5" >0.00518%</td>
    </tr>
    <tr>
      <th id="T_42c7e_level0_row30" class="row_heading level0 row30" >Drand48Mix</th>
      <td id="T_42c7e_row30_col0" class="data row30 col0" >0.00388%</td>
      <td id="T_42c7e_row30_col1" class="data row30 col1" >0.00033%</td>
      <td id="T_42c7e_row30_col2" class="data row30 col2" >0.00065%</td>
      <td id="T_42c7e_row30_col3" class="data row30 col3" >0.00123%</td>
      <td id="T_42c7e_row30_col4" class="data row30 col4" >0.00006%</td>
      <td id="T_42c7e_row30_col5" class="data row30 col5" >0.00344%</td>
    </tr>
  </tbody>
</table>

### Maximum mean error per column

In [10]:
df_mean.max()

Exponential    0.00388
Log-Normal     0.00065
Gamma          0.00134
Triangular     0.00123
Poisson        0.00029
Geometric      0.00518
dtype: float64

### Confidence interval for mean

In [11]:
conf = {}
h_list = []
for rec in data:
    name = rec["name"]
    df = rec["df"]
    for generator in generators:
        l = list(df[df["rng_mode"] == generator]["mean"])
        h = mean_confidence_interval(l)[3]  # 95%
        if name not in conf: conf[name] = []
        conf[name].append(h)
        h_list.append(h)

df_conf = pd.DataFrame(conf, index=generators)
df_conf

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric
ThreadLocalRandom,0.004344,0.000981,0.001004,0.001043,0.000284,0.003814
Random,0.003994,0.000966,0.000976,0.000960,0.000229,0.004295
SecureRandom,0.004455,0.001022,0.000968,0.000968,0.000292,0.003742
Well512a,0.003979,0.000958,0.001084,0.000840,0.000289,0.004044
Well1024a,0.003627,0.000943,0.001049,0.001062,0.000285,0.003882
Well19937a,0.003990,0.001042,0.001128,0.001077,0.000275,0.003632
Well19937c,0.004308,0.000930,0.001133,0.000994,0.000307,0.003946
Well44497a,0.004549,0.001003,0.001065,0.000982,0.000258,0.003917
Well44497b,0.003732,0.000954,0.000925,0.000917,0.000277,0.003706
MersenneTwister,0.004342,0.000920,0.000947,0.001031,0.000280,0.003593
SFC64,0.003802,0.000971,0.001044,0.001050,0.000303,0.004032
ISAAC,0.003923,0.000920,0.000962,0.000873,0.000264,0.003662
XoRoShiRo128++,0.004229,0.000965,0.001003,0.000919,0.000243,0.004189
XoRoShiRo128**,0.004065,0.001130,0.000952,0.000959,0.000293,0.003815
XoRoShiRo64**,0.004022,0.001078,0.001048,0.001066,0.000285,0.004129
XoRoShiRo256++,0.003654,0.000925,0.000973,0.001066,0.000238,0.003880
XoRoShiRo1024++,0.003851,0.001016,0.000993,0.001046,0.000290,0.003932
XoRoShiRo1024*,0.004798,0.001045,0.001010,0.001009,0.000276,0.004539
XoRoShiRo1024**,0.003444,0.001062,0.001124,0.001011,0.000247,0.003979
L32X64Mix,0.004162,0.000992,0.001047,0.000849,0.000259,0.004748
L64X128Mix,0.004173,0.000933,0.001011,0.000994,0.000247,0.004031
L64X128**,0.003737,0.000991,0.001083,0.000955,0.000277,0.003881
L64X256Mix,0.004254,0.000991,0.000984,0.000920,0.000260,0.004461
L64X1024Mix,0.003911,0.000991,0.000986,0.001023,0.000262,0.004715
L128X128Mix,0.003729,0.001045,0.000960,0.000923,0.000256,0.004058
L128X256Mix,0.004067,0.001001,0.001011,0.000894,0.000283,0.003779
L128X1024Mix,0.004376,0.000810,0.001042,0.000961,0.000303,0.003636
PcgRxsMXs64,0.004355,0.001049,0.001079,0.001041,0.000287,0.004323
Philox4x64,0.004096,0.000962,0.000992,0.000993,0.000266,0.004235
Drand48,0.016000,0.004170,0.004073,0.004156,0.001310,0.016404
Drand48Mix,0.017075,0.004434,0.004334,0.004254,0.001130,0.018278

In [12]:
print(df_conf[~df_conf.index.isin(["Drand48", "Drand48Mix"])].max())

print(df_conf[df_conf.index.isin(["Drand48", "Drand48Mix"])].max())

Exponential    0.004798
Log-Normal     0.001130
Gamma          0.001133
Triangular     0.001077
Poisson        0.000307
Geometric      0.004748
dtype: float64
Exponential    0.017075
Log-Normal     0.004434
Gamma          0.004334
Triangular     0.004254
Poisson        0.001310
Geometric      0.018278
dtype: float64

## Standard deviation

In [13]:
d = {}
for rec in data:
    d[rec["name"]] = rec["std_error"]

df_std = pd.DataFrame(d, index=generators)

df_std

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric
ThreadLocalRandom,0.00043,0.00130,0.00004,0.00134,0.00057,0.00118
Random,0.00149,0.00039,0.00191,0.00166,0.00057,0.00138
SecureRandom,0.00077,0.00384,0.00062,0.00219,0.00132,0.00172
Well512a,0.00049,0.00144,0.00343,0.00262,0.00120,0.00085
Well1024a,0.00195,0.00268,0.00073,0.00219,0.00017,0.00017
Well19937a,0.00008,0.00151,0.00106,0.00164,0.00059,0.00042
Well19937c,0.00212,0.00023,0.00045,0.00136,0.00073,0.00052
Well44497a,0.00244,0.00365,0.00137,0.00206,0.00051,0.00291
Well44497b,0.00154,0.00158,0.00223,0.00215,0.00056,0.00119
MersenneTwister,0.00023,0.00319,0.00309,0.00299,0.00065,0.00079
SFC64,0.00073,0.00179,0.00360,0.00160,0.00069,0.00062
ISAAC,0.00078,0.00067,0.00164,0.00175,0.00002,0.00047
XoRoShiRo128++,0.00076,0.00133,0.00250,0.00216,0.00005,0.00097
XoRoShiRo128**,0.00035,0.00094,0.00186,0.00165,0.00010,0.00016
XoRoShiRo64**,0.00153,0.00139,0.00057,0.00113,0.00021,0.00130
XoRoShiRo256++,0.00070,0.00172,0.00358,0.00097,0.00064,0.00132
XoRoShiRo1024++,0.00154,0.00171,0.00183,0.00147,0.00025,0.00056
XoRoShiRo1024*,0.00088,0.00152,0.00073,0.00037,0.00031,0.00078
XoRoShiRo1024**,0.00030,0.00196,0.00195,0.00182,0.00034,0.00432
L32X64Mix,0.00202,0.00222,0.00089,0.00114,0.00109,0.00077
L64X128Mix,0.00036,0.00122,0.00243,0.00212,0.00073,0.00224
L64X128**,0.00021,0.00075,0.00334,0.00155,0.00091,0.00016
L64X256Mix,0.00219,0.00182,0.00150,0.00127,0.00019,0.00064
L64X1024Mix,0.00144,0.00300,0.00241,0.00270,0.00047,0.00092
L128X128Mix,0.00138,0.00113,0.00117,0.00244,0.00005,0.00077
L128X256Mix,0.00005,0.00260,0.00124,0.00148,0.00074,0.00024
L128X1024Mix,0.00081,0.00194,0.00170,0.00265,0.00022,0.00091
PcgRxsMXs64,0.00103,0.00058,0.00144,0.00286,0.00062,0.00082
Philox4x64,0.00103,0.00263,0.00071,0.00144,0.00036,0.00055
Drand48,0.00844,0.00301,0.00764,0.00359,0.00177,0.00422
Drand48Mix,0.00864,0.00775,0.00484,0.00858,0.00376,0.00228

In [14]:
s = df_std.style.format("{:.3f}\\,\\%").set_caption("Standard Deviation Error (in \\%)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Standard Deviation Error (in \%)}
\begin{tabular}{lrrrrrr}
 & Exponential & Log-Normal & Gamma & Triangular & Poisson & Geometric \\
ThreadLocalRandom & 0.000\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% \\
Random & 0.001\,\% & 0.000\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.001\,\% \\
SecureRandom & 0.001\,\% & 0.004\,\% & 0.001\,\% & 0.002\,\% & 0.001\,\% & 0.002\,\% \\
Well512a & 0.000\,\% & 0.001\,\% & 0.003\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% \\
Well1024a & 0.002\,\% & 0.003\,\% & 0.001\,\% & 0.002\,\% & 0.000\,\% & 0.000\,\% \\
Well19937a & 0.000\,\% & 0.002\,\% & 0.001\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% \\
Well19937c & 0.002\,\% & 0.000\,\% & 0.000\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% \\
Well44497a & 0.002\,\% & 0.004\,\% & 0.001\,\% & 0.002\,\% & 0.001\,\% & 0.003\,\% \\
Well44497b & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.001\,\% \\
MersenneTwister & 0.000\,\% & 0.003\,\% & 0.003\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% \\
SFC64 & 0.001\,\% & 0.002\,\% & 0.004\,\% & 0.002\,\% & 0.001\,\% & 0.001\,\% \\
ISAAC & 0.001\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% & 0.000\,\% & 0.000\,\% \\
XoRoShiRo128++ & 0.001\,\% & 0.001\,\% & 0.003\,\% & 0.002\,\% & 0.000\,\% & 0.001\,\% \\
XoRoShiRo128** & 0.000\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% & 0.000\,\% & 0.000\,\% \\
XoRoShiRo64** & 0.002\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% \\
XoRoShiRo256++ & 0.001\,\% & 0.002\,\% & 0.004\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% \\
XoRoShiRo1024++ & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% \\
XoRoShiRo1024* & 0.001\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% & 0.000\,\% & 0.001\,\% \\
XoRoShiRo1024** & 0.000\,\% & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.000\,\% & 0.004\,\% \\
L32X64Mix & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% \\
L64X128Mix & 0.000\,\% & 0.001\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.002\,\% \\
L64X128** & 0.000\,\% & 0.001\,\% & 0.003\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% \\
L64X256Mix & 0.002\,\% & 0.002\,\% & 0.002\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% \\
L64X1024Mix & 0.001\,\% & 0.003\,\% & 0.002\,\% & 0.003\,\% & 0.000\,\% & 0.001\,\% \\
L128X128Mix & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.002\,\% & 0.000\,\% & 0.001\,\% \\
L128X256Mix & 0.000\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.000\,\% \\
L128X1024Mix & 0.001\,\% & 0.002\,\% & 0.002\,\% & 0.003\,\% & 0.000\,\% & 0.001\,\% \\
PcgRxsMXs64 & 0.001\,\% & 0.001\,\% & 0.001\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% \\
Philox4x64 & 0.001\,\% & 0.003\,\% & 0.001\,\% & 0.001\,\% & 0.000\,\% & 0.001\,\% \\
Drand48 & 0.008\,\% & 0.003\,\% & 0.008\,\% & 0.004\,\% & 0.002\,\% & 0.004\,\% \\
Drand48Mix & 0.009\,\% & 0.008\,\% & 0.005\,\% & 0.009\,\% & 0.004\,\% & 0.002\,\% \\
\end{tabular}
\end{table}

In [15]:
s = df_std.style.format("{:.3f}%").set_caption("Standard Deviation Error (in %)")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_255c9">
  <caption>Standard Deviation Error (in %)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_255c9_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_255c9_level0_col1" class="col_heading level0 col1" >Log-Normal</th>
      <th id="T_255c9_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_255c9_level0_col3" class="col_heading level0 col3" >Triangular</th>
      <th id="T_255c9_level0_col4" class="col_heading level0 col4" >Poisson</th>
      <th id="T_255c9_level0_col5" class="col_heading level0 col5" >Geometric</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_255c9_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_255c9_row0_col0" class="data row0 col0" >0.000%</td>
      <td id="T_255c9_row0_col1" class="data row0 col1" >0.001%</td>
      <td id="T_255c9_row0_col2" class="data row0 col2" >0.000%</td>
      <td id="T_255c9_row0_col3" class="data row0 col3" >0.001%</td>
      <td id="T_255c9_row0_col4" class="data row0 col4" >0.001%</td>
      <td id="T_255c9_row0_col5" class="data row0 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_255c9_row1_col0" class="data row1 col0" >0.001%</td>
      <td id="T_255c9_row1_col1" class="data row1 col1" >0.000%</td>
      <td id="T_255c9_row1_col2" class="data row1 col2" >0.002%</td>
      <td id="T_255c9_row1_col3" class="data row1 col3" >0.002%</td>
      <td id="T_255c9_row1_col4" class="data row1 col4" >0.001%</td>
      <td id="T_255c9_row1_col5" class="data row1 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_255c9_row2_col0" class="data row2 col0" >0.001%</td>
      <td id="T_255c9_row2_col1" class="data row2 col1" >0.004%</td>
      <td id="T_255c9_row2_col2" class="data row2 col2" >0.001%</td>
      <td id="T_255c9_row2_col3" class="data row2 col3" >0.002%</td>
      <td id="T_255c9_row2_col4" class="data row2 col4" >0.001%</td>
      <td id="T_255c9_row2_col5" class="data row2 col5" >0.002%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_255c9_row3_col0" class="data row3 col0" >0.000%</td>
      <td id="T_255c9_row3_col1" class="data row3 col1" >0.001%</td>
      <td id="T_255c9_row3_col2" class="data row3 col2" >0.003%</td>
      <td id="T_255c9_row3_col3" class="data row3 col3" >0.003%</td>
      <td id="T_255c9_row3_col4" class="data row3 col4" >0.001%</td>
      <td id="T_255c9_row3_col5" class="data row3 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_255c9_row4_col0" class="data row4 col0" >0.002%</td>
      <td id="T_255c9_row4_col1" class="data row4 col1" >0.003%</td>
      <td id="T_255c9_row4_col2" class="data row4 col2" >0.001%</td>
      <td id="T_255c9_row4_col3" class="data row4 col3" >0.002%</td>
      <td id="T_255c9_row4_col4" class="data row4 col4" >0.000%</td>
      <td id="T_255c9_row4_col5" class="data row4 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_255c9_row5_col0" class="data row5 col0" >0.000%</td>
      <td id="T_255c9_row5_col1" class="data row5 col1" >0.002%</td>
      <td id="T_255c9_row5_col2" class="data row5 col2" >0.001%</td>
      <td id="T_255c9_row5_col3" class="data row5 col3" >0.002%</td>
      <td id="T_255c9_row5_col4" class="data row5 col4" >0.001%</td>
      <td id="T_255c9_row5_col5" class="data row5 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_255c9_row6_col0" class="data row6 col0" >0.002%</td>
      <td id="T_255c9_row6_col1" class="data row6 col1" >0.000%</td>
      <td id="T_255c9_row6_col2" class="data row6 col2" >0.000%</td>
      <td id="T_255c9_row6_col3" class="data row6 col3" >0.001%</td>
      <td id="T_255c9_row6_col4" class="data row6 col4" >0.001%</td>
      <td id="T_255c9_row6_col5" class="data row6 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_255c9_row7_col0" class="data row7 col0" >0.002%</td>
      <td id="T_255c9_row7_col1" class="data row7 col1" >0.004%</td>
      <td id="T_255c9_row7_col2" class="data row7 col2" >0.001%</td>
      <td id="T_255c9_row7_col3" class="data row7 col3" >0.002%</td>
      <td id="T_255c9_row7_col4" class="data row7 col4" >0.001%</td>
      <td id="T_255c9_row7_col5" class="data row7 col5" >0.003%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_255c9_row8_col0" class="data row8 col0" >0.002%</td>
      <td id="T_255c9_row8_col1" class="data row8 col1" >0.002%</td>
      <td id="T_255c9_row8_col2" class="data row8 col2" >0.002%</td>
      <td id="T_255c9_row8_col3" class="data row8 col3" >0.002%</td>
      <td id="T_255c9_row8_col4" class="data row8 col4" >0.001%</td>
      <td id="T_255c9_row8_col5" class="data row8 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_255c9_row9_col0" class="data row9 col0" >0.000%</td>
      <td id="T_255c9_row9_col1" class="data row9 col1" >0.003%</td>
      <td id="T_255c9_row9_col2" class="data row9 col2" >0.003%</td>
      <td id="T_255c9_row9_col3" class="data row9 col3" >0.003%</td>
      <td id="T_255c9_row9_col4" class="data row9 col4" >0.001%</td>
      <td id="T_255c9_row9_col5" class="data row9 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row10" class="row_heading level0 row10" >SFC64</th>
      <td id="T_255c9_row10_col0" class="data row10 col0" >0.001%</td>
      <td id="T_255c9_row10_col1" class="data row10 col1" >0.002%</td>
      <td id="T_255c9_row10_col2" class="data row10 col2" >0.004%</td>
      <td id="T_255c9_row10_col3" class="data row10 col3" >0.002%</td>
      <td id="T_255c9_row10_col4" class="data row10 col4" >0.001%</td>
      <td id="T_255c9_row10_col5" class="data row10 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row11" class="row_heading level0 row11" >ISAAC</th>
      <td id="T_255c9_row11_col0" class="data row11 col0" >0.001%</td>
      <td id="T_255c9_row11_col1" class="data row11 col1" >0.001%</td>
      <td id="T_255c9_row11_col2" class="data row11 col2" >0.002%</td>
      <td id="T_255c9_row11_col3" class="data row11 col3" >0.002%</td>
      <td id="T_255c9_row11_col4" class="data row11 col4" >0.000%</td>
      <td id="T_255c9_row11_col5" class="data row11 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row12" class="row_heading level0 row12" >XoRoShiRo128++</th>
      <td id="T_255c9_row12_col0" class="data row12 col0" >0.001%</td>
      <td id="T_255c9_row12_col1" class="data row12 col1" >0.001%</td>
      <td id="T_255c9_row12_col2" class="data row12 col2" >0.003%</td>
      <td id="T_255c9_row12_col3" class="data row12 col3" >0.002%</td>
      <td id="T_255c9_row12_col4" class="data row12 col4" >0.000%</td>
      <td id="T_255c9_row12_col5" class="data row12 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row13" class="row_heading level0 row13" >XoRoShiRo128**</th>
      <td id="T_255c9_row13_col0" class="data row13 col0" >0.000%</td>
      <td id="T_255c9_row13_col1" class="data row13 col1" >0.001%</td>
      <td id="T_255c9_row13_col2" class="data row13 col2" >0.002%</td>
      <td id="T_255c9_row13_col3" class="data row13 col3" >0.002%</td>
      <td id="T_255c9_row13_col4" class="data row13 col4" >0.000%</td>
      <td id="T_255c9_row13_col5" class="data row13 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row14" class="row_heading level0 row14" >XoRoShiRo64**</th>
      <td id="T_255c9_row14_col0" class="data row14 col0" >0.002%</td>
      <td id="T_255c9_row14_col1" class="data row14 col1" >0.001%</td>
      <td id="T_255c9_row14_col2" class="data row14 col2" >0.001%</td>
      <td id="T_255c9_row14_col3" class="data row14 col3" >0.001%</td>
      <td id="T_255c9_row14_col4" class="data row14 col4" >0.000%</td>
      <td id="T_255c9_row14_col5" class="data row14 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row15" class="row_heading level0 row15" >XoRoShiRo256++</th>
      <td id="T_255c9_row15_col0" class="data row15 col0" >0.001%</td>
      <td id="T_255c9_row15_col1" class="data row15 col1" >0.002%</td>
      <td id="T_255c9_row15_col2" class="data row15 col2" >0.004%</td>
      <td id="T_255c9_row15_col3" class="data row15 col3" >0.001%</td>
      <td id="T_255c9_row15_col4" class="data row15 col4" >0.001%</td>
      <td id="T_255c9_row15_col5" class="data row15 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024++</th>
      <td id="T_255c9_row16_col0" class="data row16 col0" >0.002%</td>
      <td id="T_255c9_row16_col1" class="data row16 col1" >0.002%</td>
      <td id="T_255c9_row16_col2" class="data row16 col2" >0.002%</td>
      <td id="T_255c9_row16_col3" class="data row16 col3" >0.001%</td>
      <td id="T_255c9_row16_col4" class="data row16 col4" >0.000%</td>
      <td id="T_255c9_row16_col5" class="data row16 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024*</th>
      <td id="T_255c9_row17_col0" class="data row17 col0" >0.001%</td>
      <td id="T_255c9_row17_col1" class="data row17 col1" >0.002%</td>
      <td id="T_255c9_row17_col2" class="data row17 col2" >0.001%</td>
      <td id="T_255c9_row17_col3" class="data row17 col3" >0.000%</td>
      <td id="T_255c9_row17_col4" class="data row17 col4" >0.000%</td>
      <td id="T_255c9_row17_col5" class="data row17 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row18" class="row_heading level0 row18" >XoRoShiRo1024**</th>
      <td id="T_255c9_row18_col0" class="data row18 col0" >0.000%</td>
      <td id="T_255c9_row18_col1" class="data row18 col1" >0.002%</td>
      <td id="T_255c9_row18_col2" class="data row18 col2" >0.002%</td>
      <td id="T_255c9_row18_col3" class="data row18 col3" >0.002%</td>
      <td id="T_255c9_row18_col4" class="data row18 col4" >0.000%</td>
      <td id="T_255c9_row18_col5" class="data row18 col5" >0.004%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row19" class="row_heading level0 row19" >L32X64Mix</th>
      <td id="T_255c9_row19_col0" class="data row19 col0" >0.002%</td>
      <td id="T_255c9_row19_col1" class="data row19 col1" >0.002%</td>
      <td id="T_255c9_row19_col2" class="data row19 col2" >0.001%</td>
      <td id="T_255c9_row19_col3" class="data row19 col3" >0.001%</td>
      <td id="T_255c9_row19_col4" class="data row19 col4" >0.001%</td>
      <td id="T_255c9_row19_col5" class="data row19 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row20" class="row_heading level0 row20" >L64X128Mix</th>
      <td id="T_255c9_row20_col0" class="data row20 col0" >0.000%</td>
      <td id="T_255c9_row20_col1" class="data row20 col1" >0.001%</td>
      <td id="T_255c9_row20_col2" class="data row20 col2" >0.002%</td>
      <td id="T_255c9_row20_col3" class="data row20 col3" >0.002%</td>
      <td id="T_255c9_row20_col4" class="data row20 col4" >0.001%</td>
      <td id="T_255c9_row20_col5" class="data row20 col5" >0.002%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row21" class="row_heading level0 row21" >L64X128**</th>
      <td id="T_255c9_row21_col0" class="data row21 col0" >0.000%</td>
      <td id="T_255c9_row21_col1" class="data row21 col1" >0.001%</td>
      <td id="T_255c9_row21_col2" class="data row21 col2" >0.003%</td>
      <td id="T_255c9_row21_col3" class="data row21 col3" >0.002%</td>
      <td id="T_255c9_row21_col4" class="data row21 col4" >0.001%</td>
      <td id="T_255c9_row21_col5" class="data row21 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row22" class="row_heading level0 row22" >L64X256Mix</th>
      <td id="T_255c9_row22_col0" class="data row22 col0" >0.002%</td>
      <td id="T_255c9_row22_col1" class="data row22 col1" >0.002%</td>
      <td id="T_255c9_row22_col2" class="data row22 col2" >0.002%</td>
      <td id="T_255c9_row22_col3" class="data row22 col3" >0.001%</td>
      <td id="T_255c9_row22_col4" class="data row22 col4" >0.000%</td>
      <td id="T_255c9_row22_col5" class="data row22 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row23" class="row_heading level0 row23" >L64X1024Mix</th>
      <td id="T_255c9_row23_col0" class="data row23 col0" >0.001%</td>
      <td id="T_255c9_row23_col1" class="data row23 col1" >0.003%</td>
      <td id="T_255c9_row23_col2" class="data row23 col2" >0.002%</td>
      <td id="T_255c9_row23_col3" class="data row23 col3" >0.003%</td>
      <td id="T_255c9_row23_col4" class="data row23 col4" >0.000%</td>
      <td id="T_255c9_row23_col5" class="data row23 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row24" class="row_heading level0 row24" >L128X128Mix</th>
      <td id="T_255c9_row24_col0" class="data row24 col0" >0.001%</td>
      <td id="T_255c9_row24_col1" class="data row24 col1" >0.001%</td>
      <td id="T_255c9_row24_col2" class="data row24 col2" >0.001%</td>
      <td id="T_255c9_row24_col3" class="data row24 col3" >0.002%</td>
      <td id="T_255c9_row24_col4" class="data row24 col4" >0.000%</td>
      <td id="T_255c9_row24_col5" class="data row24 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row25" class="row_heading level0 row25" >L128X256Mix</th>
      <td id="T_255c9_row25_col0" class="data row25 col0" >0.000%</td>
      <td id="T_255c9_row25_col1" class="data row25 col1" >0.003%</td>
      <td id="T_255c9_row25_col2" class="data row25 col2" >0.001%</td>
      <td id="T_255c9_row25_col3" class="data row25 col3" >0.001%</td>
      <td id="T_255c9_row25_col4" class="data row25 col4" >0.001%</td>
      <td id="T_255c9_row25_col5" class="data row25 col5" >0.000%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row26" class="row_heading level0 row26" >L128X1024Mix</th>
      <td id="T_255c9_row26_col0" class="data row26 col0" >0.001%</td>
      <td id="T_255c9_row26_col1" class="data row26 col1" >0.002%</td>
      <td id="T_255c9_row26_col2" class="data row26 col2" >0.002%</td>
      <td id="T_255c9_row26_col3" class="data row26 col3" >0.003%</td>
      <td id="T_255c9_row26_col4" class="data row26 col4" >0.000%</td>
      <td id="T_255c9_row26_col5" class="data row26 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row27" class="row_heading level0 row27" >PcgRxsMXs64</th>
      <td id="T_255c9_row27_col0" class="data row27 col0" >0.001%</td>
      <td id="T_255c9_row27_col1" class="data row27 col1" >0.001%</td>
      <td id="T_255c9_row27_col2" class="data row27 col2" >0.001%</td>
      <td id="T_255c9_row27_col3" class="data row27 col3" >0.003%</td>
      <td id="T_255c9_row27_col4" class="data row27 col4" >0.001%</td>
      <td id="T_255c9_row27_col5" class="data row27 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row28" class="row_heading level0 row28" >Philox4x64</th>
      <td id="T_255c9_row28_col0" class="data row28 col0" >0.001%</td>
      <td id="T_255c9_row28_col1" class="data row28 col1" >0.003%</td>
      <td id="T_255c9_row28_col2" class="data row28 col2" >0.001%</td>
      <td id="T_255c9_row28_col3" class="data row28 col3" >0.001%</td>
      <td id="T_255c9_row28_col4" class="data row28 col4" >0.000%</td>
      <td id="T_255c9_row28_col5" class="data row28 col5" >0.001%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row29" class="row_heading level0 row29" >Drand48</th>
      <td id="T_255c9_row29_col0" class="data row29 col0" >0.008%</td>
      <td id="T_255c9_row29_col1" class="data row29 col1" >0.003%</td>
      <td id="T_255c9_row29_col2" class="data row29 col2" >0.008%</td>
      <td id="T_255c9_row29_col3" class="data row29 col3" >0.004%</td>
      <td id="T_255c9_row29_col4" class="data row29 col4" >0.002%</td>
      <td id="T_255c9_row29_col5" class="data row29 col5" >0.004%</td>
    </tr>
    <tr>
      <th id="T_255c9_level0_row30" class="row_heading level0 row30" >Drand48Mix</th>
      <td id="T_255c9_row30_col0" class="data row30 col0" >0.009%</td>
      <td id="T_255c9_row30_col1" class="data row30 col1" >0.008%</td>
      <td id="T_255c9_row30_col2" class="data row30 col2" >0.005%</td>
      <td id="T_255c9_row30_col3" class="data row30 col3" >0.009%</td>
      <td id="T_255c9_row30_col4" class="data row30 col4" >0.004%</td>
      <td id="T_255c9_row30_col5" class="data row30 col5" >0.002%</td>
    </tr>
  </tbody>
</table>

### Confidence interval for standard deviation

In [16]:
conf = {}
h_list = []
for rec in data:
    name = rec["name"]
    df = rec["df"]
    for generator in generators:
        l = list(df[df["rng_mode"] == generator]["std"])
        h = mean_confidence_interval(l)[3]  # 95%
        if name not in conf: conf[name] = []
        conf[name].append(h)
        h_list.append(h)

df_conf = pd.DataFrame(conf, index=generators)
df_conf

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric
ThreadLocalRandom,0.005982,0.000951,0.000745,0.000580,0.000206,0.005912
Random,0.005652,0.000894,0.000814,0.000659,0.000189,0.005909
SecureRandom,0.005372,0.000884,0.000846,0.000538,0.000184,0.006103
Well512a,0.005021,0.000865,0.000711,0.000578,0.000205,0.005933
Well1024a,0.005557,0.000874,0.000794,0.000527,0.000208,0.006038
Well19937a,0.005043,0.000906,0.000806,0.000614,0.000199,0.005292
Well19937c,0.006280,0.000841,0.000699,0.000583,0.000207,0.005882
Well44497a,0.005831,0.000841,0.000777,0.000572,0.000208,0.005470
Well44497b,0.005157,0.000895,0.000788,0.000567,0.000199,0.005370
MersenneTwister,0.006024,0.000824,0.000742,0.000523,0.000199,0.005676
SFC64,0.005544,0.000890,0.000733,0.000687,0.000204,0.006321
ISAAC,0.006105,0.000745,0.000619,0.000631,0.000190,0.005641
XoRoShiRo128++,0.005433,0.000868,0.000813,0.000701,0.000202,0.006664
XoRoShiRo128**,0.005807,0.000904,0.000806,0.000547,0.000193,0.006127
XoRoShiRo64**,0.005504,0.000928,0.000789,0.000587,0.000187,0.005269
XoRoShiRo256++,0.005637,0.000781,0.000763,0.000550,0.000219,0.005651
XoRoShiRo1024++,0.005681,0.000885,0.000855,0.000579,0.000195,0.006060
XoRoShiRo1024*,0.006062,0.000876,0.000832,0.000596,0.000208,0.006477
XoRoShiRo1024**,0.004402,0.000922,0.000795,0.000591,0.000204,0.005720
L32X64Mix,0.005561,0.000795,0.000728,0.000603,0.000214,0.005838
L64X128Mix,0.005839,0.000808,0.000741,0.000529,0.000210,0.005724
L64X128**,0.005434,0.000904,0.000724,0.000572,0.000216,0.005415
L64X256Mix,0.005513,0.000851,0.000819,0.000621,0.000212,0.005944
L64X1024Mix,0.006379,0.000753,0.000755,0.000602,0.000194,0.006557
L128X128Mix,0.005473,0.000854,0.000789,0.000547,0.000199,0.005413
L128X256Mix,0.006024,0.000777,0.000876,0.000644,0.000216,0.005097
L128X1024Mix,0.005779,0.000796,0.000717,0.000573,0.000198,0.004878
PcgRxsMXs64,0.005657,0.000755,0.000783,0.000607,0.000233,0.005953
Philox4x64,0.005559,0.000851,0.000810,0.000671,0.000210,0.006100
Drand48,0.024665,0.003770,0.003128,0.002465,0.000845,0.023109
Drand48Mix,0.023000,0.003701,0.003062,0.002479,0.000815,0.026110

In [17]:
print(df_conf[(df_conf.index != "Drand48") & (df_conf.index != "Drand48Mix")].max())
print(df_conf[df_conf.index == "Drand48"].max())
print(df_conf[df_conf.index == "Drand48Mix"].max())

Exponential    0.006379
Log-Normal     0.000951
Gamma          0.000876
Triangular     0.000701
Poisson        0.000233
Geometric      0.006664
dtype: float64
Exponential    0.024665
Log-Normal     0.003770
Gamma          0.003128
Triangular     0.002465
Poisson        0.000845
Geometric      0.023109
dtype: float64
Exponential    0.023000
Log-Normal     0.003701
Gamma          0.003062
Triangular     0.002479
Poisson        0.000815
Geometric      0.026110
dtype: float64

## $\Delta^2$

In [18]:
d = {}
for rec in data:
    d[rec["name"]] = rec["delta2"]

df_delta2 = pd.DataFrame(d, index=generators)

df_delta2

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric
ThreadLocalRandom,1.00455,1.00277,0.98729,0.99899,1.00564,1.00281
Random,1.00700,0.99318,0.98839,0.98315,1.00623,0.99248
SecureRandom,0.99348,0.99321,1.00888,0.99872,0.98711,0.99437
Well512a,0.99287,0.98008,1.00308,0.98627,0.95551,1.00290
Well1024a,0.99958,0.98315,1.00869,0.99681,1.02409,0.99613
Well19937a,0.99603,1.00379,1.00374,0.98767,1.00879,1.01312
Well19937c,1.00755,0.97541,0.99641,0.98882,0.97230,1.00440
Well44497a,0.99034,1.00254,0.99169,0.99690,0.99962,0.99379
Well44497b,1.00261,1.00373,1.00126,1.01602,0.96665,0.99878
MersenneTwister,1.01001,0.99174,0.98136,0.99030,0.99799,1.00015
SFC64,1.03806,1.03675,1.02216,1.14453,0.95765,1.01954
ISAAC,0.99151,0.97346,0.99425,0.98423,0.99760,0.99843
XoRoShiRo128++,1.02216,1.03359,1.03346,1.05463,0.95941,0.99882
XoRoShiRo128**,1.03056,1.02448,1.01038,1.00643,0.97609,1.01706
XoRoShiRo64**,1.02839,1.02591,1.03440,1.04178,1.00872,1.02325
XoRoShiRo256++,1.00447,0.98587,0.99761,0.99858,0.96210,0.99122
XoRoShiRo1024++,1.00267,1.00767,1.01301,1.07092,1.00488,1.04388
XoRoShiRo1024*,1.02996,1.01117,1.01979,1.06401,1.00707,1.01529
XoRoShiRo1024**,1.01952,1.01547,1.02551,1.05635,0.99887,1.03529
L32X64Mix,1.03082,1.00588,1.01232,1.01115,0.99955,1.02171
L64X128Mix,0.99925,0.99980,0.99630,0.97251,0.99659,0.98760
L64X128**,0.99898,1.00217,0.99554,0.99706,0.97269,1.00273
L64X256Mix,1.00033,1.00158,0.98481,1.00123,0.97249,0.99627
L64X1024Mix,0.98923,0.99999,0.99373,0.99336,0.96878,1.00386
L128X128Mix,0.98769,1.00043,0.98558,1.01031,0.96919,0.99331
L128X256Mix,0.99065,0.99020,1.00231,0.97990,1.00924,1.00306
L128X1024Mix,0.99920,0.98113,0.98865,1.00645,1.02258,0.99897
PcgRxsMXs64,1.04505,1.03355,1.03706,1.04303,1.04217,1.01333
Philox4x64,1.02172,1.02551,0.99434,1.05822,1.03939,1.01468
Drand48,16.56192,18.52441,16.45777,17.56581,17.76290,20.42273
Drand48Mix,19.47353,20.13199,20.36621,19.23310,17.88241,20.62087

In [19]:
df_delta2[(df_delta2.index != "Drand48") & (df_delta2.index != "Drand48Mix")].max()

Exponential    1.04505
Log-Normal     1.03675
Gamma          1.03706
Triangular     1.14453
Poisson        1.04217
Geometric      1.04388
dtype: float64

In [20]:
s = df_delta2.style.format("{:.2f}").set_caption("$\\Delta^2$").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{$\Delta^2$}
\begin{tabular}{lrrrrrr}
 & Exponential & Log-Normal & Gamma & Triangular & Poisson & Geometric \\
ThreadLocalRandom & 1.00 & 1.00 & 0.99 & 1.00 & 1.01 & 1.00 \\
Random & 1.01 & 0.99 & 0.99 & 0.98 & 1.01 & 0.99 \\
SecureRandom & 0.99 & 0.99 & 1.01 & 1.00 & 0.99 & 0.99 \\
Well512a & 0.99 & 0.98 & 1.00 & 0.99 & 0.96 & 1.00 \\
Well1024a & 1.00 & 0.98 & 1.01 & 1.00 & 1.02 & 1.00 \\
Well19937a & 1.00 & 1.00 & 1.00 & 0.99 & 1.01 & 1.01 \\
Well19937c & 1.01 & 0.98 & 1.00 & 0.99 & 0.97 & 1.00 \\
Well44497a & 0.99 & 1.00 & 0.99 & 1.00 & 1.00 & 0.99 \\
Well44497b & 1.00 & 1.00 & 1.00 & 1.02 & 0.97 & 1.00 \\
MersenneTwister & 1.01 & 0.99 & 0.98 & 0.99 & 1.00 & 1.00 \\
SFC64 & 1.04 & 1.04 & 1.02 & 1.14 & 0.96 & 1.02 \\
ISAAC & 0.99 & 0.97 & 0.99 & 0.98 & 1.00 & 1.00 \\
XoRoShiRo128++ & 1.02 & 1.03 & 1.03 & 1.05 & 0.96 & 1.00 \\
XoRoShiRo128** & 1.03 & 1.02 & 1.01 & 1.01 & 0.98 & 1.02 \\
XoRoShiRo64** & 1.03 & 1.03 & 1.03 & 1.04 & 1.01 & 1.02 \\
XoRoShiRo256++ & 1.00 & 0.99 & 1.00 & 1.00 & 0.96 & 0.99 \\
XoRoShiRo1024++ & 1.00 & 1.01 & 1.01 & 1.07 & 1.00 & 1.04 \\
XoRoShiRo1024* & 1.03 & 1.01 & 1.02 & 1.06 & 1.01 & 1.02 \\
XoRoShiRo1024** & 1.02 & 1.02 & 1.03 & 1.06 & 1.00 & 1.04 \\
L32X64Mix & 1.03 & 1.01 & 1.01 & 1.01 & 1.00 & 1.02 \\
L64X128Mix & 1.00 & 1.00 & 1.00 & 0.97 & 1.00 & 0.99 \\
L64X128** & 1.00 & 1.00 & 1.00 & 1.00 & 0.97 & 1.00 \\
L64X256Mix & 1.00 & 1.00 & 0.98 & 1.00 & 0.97 & 1.00 \\
L64X1024Mix & 0.99 & 1.00 & 0.99 & 0.99 & 0.97 & 1.00 \\
L128X128Mix & 0.99 & 1.00 & 0.99 & 1.01 & 0.97 & 0.99 \\
L128X256Mix & 0.99 & 0.99 & 1.00 & 0.98 & 1.01 & 1.00 \\
L128X1024Mix & 1.00 & 0.98 & 0.99 & 1.01 & 1.02 & 1.00 \\
PcgRxsMXs64 & 1.05 & 1.03 & 1.04 & 1.04 & 1.04 & 1.01 \\
Philox4x64 & 1.02 & 1.03 & 0.99 & 1.06 & 1.04 & 1.01 \\
Drand48 & 16.56 & 18.52 & 16.46 & 17.57 & 17.76 & 20.42 \\
Drand48Mix & 19.47 & 20.13 & 20.37 & 19.23 & 17.88 & 20.62 \\
\end{tabular}
\end{table}

In [21]:
s = df_delta2.style.format("{:.2f}").set_caption("&Delta;<sup>2</sup>")
print(s.to_html())

<style type="text/css">
</style>
<table id="T_621b7">
  <caption>&Delta;<sup>2</sup></caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_621b7_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_621b7_level0_col1" class="col_heading level0 col1" >Log-Normal</th>
      <th id="T_621b7_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_621b7_level0_col3" class="col_heading level0 col3" >Triangular</th>
      <th id="T_621b7_level0_col4" class="col_heading level0 col4" >Poisson</th>
      <th id="T_621b7_level0_col5" class="col_heading level0 col5" >Geometric</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_621b7_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_621b7_row0_col0" class="data row0 col0" >1.00</td>
      <td id="T_621b7_row0_col1" class="data row0 col1" >1.00</td>
      <td id="T_621b7_row0_col2" class="data row0 col2" >0.99</td>
      <td id="T_621b7_row0_col3" class="data row0 col3" >1.00</td>
      <td id="T_621b7_row0_col4" class="data row0 col4" >1.01</td>
      <td id="T_621b7_row0_col5" class="data row0 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_621b7_row1_col0" class="data row1 col0" >1.01</td>
      <td id="T_621b7_row1_col1" class="data row1 col1" >0.99</td>
      <td id="T_621b7_row1_col2" class="data row1 col2" >0.99</td>
      <td id="T_621b7_row1_col3" class="data row1 col3" >0.98</td>
      <td id="T_621b7_row1_col4" class="data row1 col4" >1.01</td>
      <td id="T_621b7_row1_col5" class="data row1 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_621b7_row2_col0" class="data row2 col0" >0.99</td>
      <td id="T_621b7_row2_col1" class="data row2 col1" >0.99</td>
      <td id="T_621b7_row2_col2" class="data row2 col2" >1.01</td>
      <td id="T_621b7_row2_col3" class="data row2 col3" >1.00</td>
      <td id="T_621b7_row2_col4" class="data row2 col4" >0.99</td>
      <td id="T_621b7_row2_col5" class="data row2 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_621b7_row3_col0" class="data row3 col0" >0.99</td>
      <td id="T_621b7_row3_col1" class="data row3 col1" >0.98</td>
      <td id="T_621b7_row3_col2" class="data row3 col2" >1.00</td>
      <td id="T_621b7_row3_col3" class="data row3 col3" >0.99</td>
      <td id="T_621b7_row3_col4" class="data row3 col4" >0.96</td>
      <td id="T_621b7_row3_col5" class="data row3 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_621b7_row4_col0" class="data row4 col0" >1.00</td>
      <td id="T_621b7_row4_col1" class="data row4 col1" >0.98</td>
      <td id="T_621b7_row4_col2" class="data row4 col2" >1.01</td>
      <td id="T_621b7_row4_col3" class="data row4 col3" >1.00</td>
      <td id="T_621b7_row4_col4" class="data row4 col4" >1.02</td>
      <td id="T_621b7_row4_col5" class="data row4 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_621b7_row5_col0" class="data row5 col0" >1.00</td>
      <td id="T_621b7_row5_col1" class="data row5 col1" >1.00</td>
      <td id="T_621b7_row5_col2" class="data row5 col2" >1.00</td>
      <td id="T_621b7_row5_col3" class="data row5 col3" >0.99</td>
      <td id="T_621b7_row5_col4" class="data row5 col4" >1.01</td>
      <td id="T_621b7_row5_col5" class="data row5 col5" >1.01</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_621b7_row6_col0" class="data row6 col0" >1.01</td>
      <td id="T_621b7_row6_col1" class="data row6 col1" >0.98</td>
      <td id="T_621b7_row6_col2" class="data row6 col2" >1.00</td>
      <td id="T_621b7_row6_col3" class="data row6 col3" >0.99</td>
      <td id="T_621b7_row6_col4" class="data row6 col4" >0.97</td>
      <td id="T_621b7_row6_col5" class="data row6 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_621b7_row7_col0" class="data row7 col0" >0.99</td>
      <td id="T_621b7_row7_col1" class="data row7 col1" >1.00</td>
      <td id="T_621b7_row7_col2" class="data row7 col2" >0.99</td>
      <td id="T_621b7_row7_col3" class="data row7 col3" >1.00</td>
      <td id="T_621b7_row7_col4" class="data row7 col4" >1.00</td>
      <td id="T_621b7_row7_col5" class="data row7 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_621b7_row8_col0" class="data row8 col0" >1.00</td>
      <td id="T_621b7_row8_col1" class="data row8 col1" >1.00</td>
      <td id="T_621b7_row8_col2" class="data row8 col2" >1.00</td>
      <td id="T_621b7_row8_col3" class="data row8 col3" >1.02</td>
      <td id="T_621b7_row8_col4" class="data row8 col4" >0.97</td>
      <td id="T_621b7_row8_col5" class="data row8 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_621b7_row9_col0" class="data row9 col0" >1.01</td>
      <td id="T_621b7_row9_col1" class="data row9 col1" >0.99</td>
      <td id="T_621b7_row9_col2" class="data row9 col2" >0.98</td>
      <td id="T_621b7_row9_col3" class="data row9 col3" >0.99</td>
      <td id="T_621b7_row9_col4" class="data row9 col4" >1.00</td>
      <td id="T_621b7_row9_col5" class="data row9 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row10" class="row_heading level0 row10" >SFC64</th>
      <td id="T_621b7_row10_col0" class="data row10 col0" >1.04</td>
      <td id="T_621b7_row10_col1" class="data row10 col1" >1.04</td>
      <td id="T_621b7_row10_col2" class="data row10 col2" >1.02</td>
      <td id="T_621b7_row10_col3" class="data row10 col3" >1.14</td>
      <td id="T_621b7_row10_col4" class="data row10 col4" >0.96</td>
      <td id="T_621b7_row10_col5" class="data row10 col5" >1.02</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row11" class="row_heading level0 row11" >ISAAC</th>
      <td id="T_621b7_row11_col0" class="data row11 col0" >0.99</td>
      <td id="T_621b7_row11_col1" class="data row11 col1" >0.97</td>
      <td id="T_621b7_row11_col2" class="data row11 col2" >0.99</td>
      <td id="T_621b7_row11_col3" class="data row11 col3" >0.98</td>
      <td id="T_621b7_row11_col4" class="data row11 col4" >1.00</td>
      <td id="T_621b7_row11_col5" class="data row11 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row12" class="row_heading level0 row12" >XoRoShiRo128++</th>
      <td id="T_621b7_row12_col0" class="data row12 col0" >1.02</td>
      <td id="T_621b7_row12_col1" class="data row12 col1" >1.03</td>
      <td id="T_621b7_row12_col2" class="data row12 col2" >1.03</td>
      <td id="T_621b7_row12_col3" class="data row12 col3" >1.05</td>
      <td id="T_621b7_row12_col4" class="data row12 col4" >0.96</td>
      <td id="T_621b7_row12_col5" class="data row12 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row13" class="row_heading level0 row13" >XoRoShiRo128**</th>
      <td id="T_621b7_row13_col0" class="data row13 col0" >1.03</td>
      <td id="T_621b7_row13_col1" class="data row13 col1" >1.02</td>
      <td id="T_621b7_row13_col2" class="data row13 col2" >1.01</td>
      <td id="T_621b7_row13_col3" class="data row13 col3" >1.01</td>
      <td id="T_621b7_row13_col4" class="data row13 col4" >0.98</td>
      <td id="T_621b7_row13_col5" class="data row13 col5" >1.02</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row14" class="row_heading level0 row14" >XoRoShiRo64**</th>
      <td id="T_621b7_row14_col0" class="data row14 col0" >1.03</td>
      <td id="T_621b7_row14_col1" class="data row14 col1" >1.03</td>
      <td id="T_621b7_row14_col2" class="data row14 col2" >1.03</td>
      <td id="T_621b7_row14_col3" class="data row14 col3" >1.04</td>
      <td id="T_621b7_row14_col4" class="data row14 col4" >1.01</td>
      <td id="T_621b7_row14_col5" class="data row14 col5" >1.02</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row15" class="row_heading level0 row15" >XoRoShiRo256++</th>
      <td id="T_621b7_row15_col0" class="data row15 col0" >1.00</td>
      <td id="T_621b7_row15_col1" class="data row15 col1" >0.99</td>
      <td id="T_621b7_row15_col2" class="data row15 col2" >1.00</td>
      <td id="T_621b7_row15_col3" class="data row15 col3" >1.00</td>
      <td id="T_621b7_row15_col4" class="data row15 col4" >0.96</td>
      <td id="T_621b7_row15_col5" class="data row15 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024++</th>
      <td id="T_621b7_row16_col0" class="data row16 col0" >1.00</td>
      <td id="T_621b7_row16_col1" class="data row16 col1" >1.01</td>
      <td id="T_621b7_row16_col2" class="data row16 col2" >1.01</td>
      <td id="T_621b7_row16_col3" class="data row16 col3" >1.07</td>
      <td id="T_621b7_row16_col4" class="data row16 col4" >1.00</td>
      <td id="T_621b7_row16_col5" class="data row16 col5" >1.04</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024*</th>
      <td id="T_621b7_row17_col0" class="data row17 col0" >1.03</td>
      <td id="T_621b7_row17_col1" class="data row17 col1" >1.01</td>
      <td id="T_621b7_row17_col2" class="data row17 col2" >1.02</td>
      <td id="T_621b7_row17_col3" class="data row17 col3" >1.06</td>
      <td id="T_621b7_row17_col4" class="data row17 col4" >1.01</td>
      <td id="T_621b7_row17_col5" class="data row17 col5" >1.02</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row18" class="row_heading level0 row18" >XoRoShiRo1024**</th>
      <td id="T_621b7_row18_col0" class="data row18 col0" >1.02</td>
      <td id="T_621b7_row18_col1" class="data row18 col1" >1.02</td>
      <td id="T_621b7_row18_col2" class="data row18 col2" >1.03</td>
      <td id="T_621b7_row18_col3" class="data row18 col3" >1.06</td>
      <td id="T_621b7_row18_col4" class="data row18 col4" >1.00</td>
      <td id="T_621b7_row18_col5" class="data row18 col5" >1.04</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row19" class="row_heading level0 row19" >L32X64Mix</th>
      <td id="T_621b7_row19_col0" class="data row19 col0" >1.03</td>
      <td id="T_621b7_row19_col1" class="data row19 col1" >1.01</td>
      <td id="T_621b7_row19_col2" class="data row19 col2" >1.01</td>
      <td id="T_621b7_row19_col3" class="data row19 col3" >1.01</td>
      <td id="T_621b7_row19_col4" class="data row19 col4" >1.00</td>
      <td id="T_621b7_row19_col5" class="data row19 col5" >1.02</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row20" class="row_heading level0 row20" >L64X128Mix</th>
      <td id="T_621b7_row20_col0" class="data row20 col0" >1.00</td>
      <td id="T_621b7_row20_col1" class="data row20 col1" >1.00</td>
      <td id="T_621b7_row20_col2" class="data row20 col2" >1.00</td>
      <td id="T_621b7_row20_col3" class="data row20 col3" >0.97</td>
      <td id="T_621b7_row20_col4" class="data row20 col4" >1.00</td>
      <td id="T_621b7_row20_col5" class="data row20 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row21" class="row_heading level0 row21" >L64X128**</th>
      <td id="T_621b7_row21_col0" class="data row21 col0" >1.00</td>
      <td id="T_621b7_row21_col1" class="data row21 col1" >1.00</td>
      <td id="T_621b7_row21_col2" class="data row21 col2" >1.00</td>
      <td id="T_621b7_row21_col3" class="data row21 col3" >1.00</td>
      <td id="T_621b7_row21_col4" class="data row21 col4" >0.97</td>
      <td id="T_621b7_row21_col5" class="data row21 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row22" class="row_heading level0 row22" >L64X256Mix</th>
      <td id="T_621b7_row22_col0" class="data row22 col0" >1.00</td>
      <td id="T_621b7_row22_col1" class="data row22 col1" >1.00</td>
      <td id="T_621b7_row22_col2" class="data row22 col2" >0.98</td>
      <td id="T_621b7_row22_col3" class="data row22 col3" >1.00</td>
      <td id="T_621b7_row22_col4" class="data row22 col4" >0.97</td>
      <td id="T_621b7_row22_col5" class="data row22 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row23" class="row_heading level0 row23" >L64X1024Mix</th>
      <td id="T_621b7_row23_col0" class="data row23 col0" >0.99</td>
      <td id="T_621b7_row23_col1" class="data row23 col1" >1.00</td>
      <td id="T_621b7_row23_col2" class="data row23 col2" >0.99</td>
      <td id="T_621b7_row23_col3" class="data row23 col3" >0.99</td>
      <td id="T_621b7_row23_col4" class="data row23 col4" >0.97</td>
      <td id="T_621b7_row23_col5" class="data row23 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row24" class="row_heading level0 row24" >L128X128Mix</th>
      <td id="T_621b7_row24_col0" class="data row24 col0" >0.99</td>
      <td id="T_621b7_row24_col1" class="data row24 col1" >1.00</td>
      <td id="T_621b7_row24_col2" class="data row24 col2" >0.99</td>
      <td id="T_621b7_row24_col3" class="data row24 col3" >1.01</td>
      <td id="T_621b7_row24_col4" class="data row24 col4" >0.97</td>
      <td id="T_621b7_row24_col5" class="data row24 col5" >0.99</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row25" class="row_heading level0 row25" >L128X256Mix</th>
      <td id="T_621b7_row25_col0" class="data row25 col0" >0.99</td>
      <td id="T_621b7_row25_col1" class="data row25 col1" >0.99</td>
      <td id="T_621b7_row25_col2" class="data row25 col2" >1.00</td>
      <td id="T_621b7_row25_col3" class="data row25 col3" >0.98</td>
      <td id="T_621b7_row25_col4" class="data row25 col4" >1.01</td>
      <td id="T_621b7_row25_col5" class="data row25 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row26" class="row_heading level0 row26" >L128X1024Mix</th>
      <td id="T_621b7_row26_col0" class="data row26 col0" >1.00</td>
      <td id="T_621b7_row26_col1" class="data row26 col1" >0.98</td>
      <td id="T_621b7_row26_col2" class="data row26 col2" >0.99</td>
      <td id="T_621b7_row26_col3" class="data row26 col3" >1.01</td>
      <td id="T_621b7_row26_col4" class="data row26 col4" >1.02</td>
      <td id="T_621b7_row26_col5" class="data row26 col5" >1.00</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row27" class="row_heading level0 row27" >PcgRxsMXs64</th>
      <td id="T_621b7_row27_col0" class="data row27 col0" >1.05</td>
      <td id="T_621b7_row27_col1" class="data row27 col1" >1.03</td>
      <td id="T_621b7_row27_col2" class="data row27 col2" >1.04</td>
      <td id="T_621b7_row27_col3" class="data row27 col3" >1.04</td>
      <td id="T_621b7_row27_col4" class="data row27 col4" >1.04</td>
      <td id="T_621b7_row27_col5" class="data row27 col5" >1.01</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row28" class="row_heading level0 row28" >Philox4x64</th>
      <td id="T_621b7_row28_col0" class="data row28 col0" >1.02</td>
      <td id="T_621b7_row28_col1" class="data row28 col1" >1.03</td>
      <td id="T_621b7_row28_col2" class="data row28 col2" >0.99</td>
      <td id="T_621b7_row28_col3" class="data row28 col3" >1.06</td>
      <td id="T_621b7_row28_col4" class="data row28 col4" >1.04</td>
      <td id="T_621b7_row28_col5" class="data row28 col5" >1.01</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row29" class="row_heading level0 row29" >Drand48</th>
      <td id="T_621b7_row29_col0" class="data row29 col0" >16.56</td>
      <td id="T_621b7_row29_col1" class="data row29 col1" >18.52</td>
      <td id="T_621b7_row29_col2" class="data row29 col2" >16.46</td>
      <td id="T_621b7_row29_col3" class="data row29 col3" >17.57</td>
      <td id="T_621b7_row29_col4" class="data row29 col4" >17.76</td>
      <td id="T_621b7_row29_col5" class="data row29 col5" >20.42</td>
    </tr>
    <tr>
      <th id="T_621b7_level0_row30" class="row_heading level0 row30" >Drand48Mix</th>
      <td id="T_621b7_row30_col0" class="data row30 col0" >19.47</td>
      <td id="T_621b7_row30_col1" class="data row30 col1" >20.13</td>
      <td id="T_621b7_row30_col2" class="data row30 col2" >20.37</td>
      <td id="T_621b7_row30_col3" class="data row30 col3" >19.23</td>
      <td id="T_621b7_row30_col4" class="data row30 col4" >17.88</td>
      <td id="T_621b7_row30_col5" class="data row30 col5" >20.62</td>
    </tr>
  </tbody>
</table>

## Times

In [22]:
generators.append("ThreadLocalRandomSlow")  # Not in quality comparison list since only used for speed comparision

for rec in data:
    df = rec["df"]
    mean = rec["mean"]
    std = rec["std"]

    mean_error = []
    std_error = []
    delta2 = []
    time = []

    for generator in generators:
        mean_error.append(round(abs(df[df["rng_mode"] == generator]["mean"].mean() - mean) / mean * 100, 5))  # Values are in percentage
        std_error.append(round(abs(df[df["rng_mode"] == generator]["std"].mean() - std) / std * 100, 5))  # Values are in percentage
        delta2.append(round(df[df["rng_mode"] == generator]["delta2"].mean() * 100000000, 5))
        time.append(round(df[df["rng_mode"] == generator]["time"].mean(), 5))

    rec["mean_error"] = mean_error
    rec["std_error"] = std_error
    rec["delta2"] = delta2
    rec["time"] = time

In [23]:
average_time = [sum([data[i]["time"][j] for i in range(len(data))]) for j in range(len(generators))]

d = {}
for rec in data:
    d[rec["name"]] = rec["time"]/min(rec["time"])*100

d["Average"] = average_time/np.min(average_time)*100

df_time = pd.DataFrame(d, index=generators)

df_time

,Exponential,Log-Normal,Gamma,Triangular,Poisson,Geometric,Average
ThreadLocalRandom,106.566215,100.000000,100.000000,107.220010,100.398897,102.535558,101.353519
Random,108.161936,102.005610,103.992306,106.706417,100.680586,104.771930,102.874101
SecureRandom,376.542787,411.610636,650.179512,369.569279,282.547009,360.674909,396.318652
Well512a,108.580389,108.509391,116.874484,112.907850,102.254913,103.455277,107.019314
Well1024a,108.536957,107.099845,117.137136,114.158039,102.259109,115.763438,108.964997
Well19937a,110.174439,112.731922,123.060426,117.003250,104.225900,108.364531,110.696598
Well19937c,111.269017,112.327217,126.854064,116.787136,106.059538,108.176947,111.747688
Well44497a,110.987542,114.114189,124.504813,116.348451,107.087271,109.612325,112.000848
Well44497b,112.514356,113.200549,127.405830,116.422068,106.254511,108.295276,112.164848
MersenneTwister,108.265088,109.415702,118.882881,111.396776,105.216148,105.730036,108.231029
SFC64,100.000000,104.305182,102.927086,100.000000,100.194133,100.000000,100.000000
ISAAC,109.490798,107.658452,122.258252,113.078330,102.737730,107.014635,108.572222
XoRoShiRo128++,102.771316,106.966300,112.448506,112.686570,101.214034,102.070554,104.728437
XoRoShiRo128**,101.294617,104.417962,113.488054,110.497449,100.695692,102.758364,103.955453
XoRoShiRo64**,101.287935,107.018822,115.479863,110.202122,100.000000,102.665363,104.456082
XoRoShiRo256++,116.577784,120.501118,122.155166,122.007017,108.040874,116.767451,115.612044
XoRoShiRo1024++,103.927284,109.334680,106.625933,103.754440,102.488489,100.686623,103.112442
XoRoShiRo1024*,107.287860,109.493060,108.478318,104.780765,102.601500,101.428255,104.224619
XoRoShiRo1024**,108.265088,109.574083,108.600363,105.618529,101.865528,103.864480,104.744755
L32X64Mix,104.571252,105.250172,113.615233,109.767312,102.444012,103.513451,104.997977
L64X128Mix,119.115651,122.656966,124.233867,122.544719,109.402047,116.393864,116.975441
L64X128**,122.731392,122.160652,125.513158,122.224423,111.002669,117.253429,118.090118
L64X256Mix,125.317286,123.163865,126.720961,123.275717,111.672905,118.564938,119.332219
L64X1024Mix,126.509586,123.822630,128.084775,124.291280,111.903123,119.393239,120.157598
L128X128Mix,123.865226,124.147127,127.971815,125.550509,111.736404,118.863728,119.855607
L128X256Mix,122.424442,123.406932,127.645969,125.681383,113.239679,119.665514,119.956333
L128X1024Mix,123.894459,124.347037,128.773199,125.736918,112.158798,120.513602,120.399691
PcgRxsMXs64,107.520474,110.351735,109.349611,105.885873,103.239567,102.095882,104.937829
Philox4x64,109.693760,113.863793,110.762006,108.252793,103.903370,105.929494,107.123917
Drand48,101.172673,105.252208,108.904091,107.672902,102.346106,100.638737,102.963448
Drand48Mix,109.864566,112.165579,115.536738,115.318251,100.452325,100.312245,107.011874
ThreadLocalRandomSlow,112.348979,115.252167,110.897479,111.799298,103.749797,102.429102,107.683819

In [24]:

s = df_time.style.format("{:.0f}\\,\\%").set_caption("Times to generate PRN (Normalized to fastest in each column)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_latex())

\begin{table}
\caption{Times to generate PRN (Normalized to fastest in each column)}
\begin{tabular}{lrrrrrrr}
 & Exponential & Log-Normal & Gamma & Triangular & Poisson & Geometric & Average \\
ThreadLocalRandom & 107\,\% & 100\,\% & 100\,\% & 107\,\% & 100\,\% & 103\,\% & 101\,\% \\
Random & 108\,\% & 102\,\% & 104\,\% & 107\,\% & 101\,\% & 105\,\% & 103\,\% \\
SecureRandom & 377\,\% & 412\,\% & 650\,\% & 370\,\% & 283\,\% & 361\,\% & 396\,\% \\
Well512a & 109\,\% & 109\,\% & 117\,\% & 113\,\% & 102\,\% & 103\,\% & 107\,\% \\
Well1024a & 109\,\% & 107\,\% & 117\,\% & 114\,\% & 102\,\% & 116\,\% & 109\,\% \\
Well19937a & 110\,\% & 113\,\% & 123\,\% & 117\,\% & 104\,\% & 108\,\% & 111\,\% \\
Well19937c & 111\,\% & 112\,\% & 127\,\% & 117\,\% & 106\,\% & 108\,\% & 112\,\% \\
Well44497a & 111\,\% & 114\,\% & 125\,\% & 116\,\% & 107\,\% & 110\,\% & 112\,\% \\
Well44497b & 113\,\% & 113\,\% & 127\,\% & 116\,\% & 106\,\% & 108\,\% & 112\,\% \\
MersenneTwister & 108\,\% & 109\,\% & 119\,\% & 111\,\% & 105\,\% & 106\,\% & 108\,\% \\
SFC64 & 100\,\% & 104\,\% & 103\,\% & 100\,\% & 100\,\% & 100\,\% & 100\,\% \\
ISAAC & 109\,\% & 108\,\% & 122\,\% & 113\,\% & 103\,\% & 107\,\% & 109\,\% \\
XoRoShiRo128++ & 103\,\% & 107\,\% & 112\,\% & 113\,\% & 101\,\% & 102\,\% & 105\,\% \\
XoRoShiRo128** & 101\,\% & 104\,\% & 113\,\% & 110\,\% & 101\,\% & 103\,\% & 104\,\% \\
XoRoShiRo64** & 101\,\% & 107\,\% & 115\,\% & 110\,\% & 100\,\% & 103\,\% & 104\,\% \\
XoRoShiRo256++ & 117\,\% & 121\,\% & 122\,\% & 122\,\% & 108\,\% & 117\,\% & 116\,\% \\
XoRoShiRo1024++ & 104\,\% & 109\,\% & 107\,\% & 104\,\% & 102\,\% & 101\,\% & 103\,\% \\
XoRoShiRo1024* & 107\,\% & 109\,\% & 108\,\% & 105\,\% & 103\,\% & 101\,\% & 104\,\% \\
XoRoShiRo1024** & 108\,\% & 110\,\% & 109\,\% & 106\,\% & 102\,\% & 104\,\% & 105\,\% \\
L32X64Mix & 105\,\% & 105\,\% & 114\,\% & 110\,\% & 102\,\% & 104\,\% & 105\,\% \\
L64X128Mix & 119\,\% & 123\,\% & 124\,\% & 123\,\% & 109\,\% & 116\,\% & 117\,\% \\
L64X128** & 123\,\% & 122\,\% & 126\,\% & 122\,\% & 111\,\% & 117\,\% & 118\,\% \\
L64X256Mix & 125\,\% & 123\,\% & 127\,\% & 123\,\% & 112\,\% & 119\,\% & 119\,\% \\
L64X1024Mix & 127\,\% & 124\,\% & 128\,\% & 124\,\% & 112\,\% & 119\,\% & 120\,\% \\
L128X128Mix & 124\,\% & 124\,\% & 128\,\% & 126\,\% & 112\,\% & 119\,\% & 120\,\% \\
L128X256Mix & 122\,\% & 123\,\% & 128\,\% & 126\,\% & 113\,\% & 120\,\% & 120\,\% \\
L128X1024Mix & 124\,\% & 124\,\% & 129\,\% & 126\,\% & 112\,\% & 121\,\% & 120\,\% \\
PcgRxsMXs64 & 108\,\% & 110\,\% & 109\,\% & 106\,\% & 103\,\% & 102\,\% & 105\,\% \\
Philox4x64 & 110\,\% & 114\,\% & 111\,\% & 108\,\% & 104\,\% & 106\,\% & 107\,\% \\
Drand48 & 101\,\% & 105\,\% & 109\,\% & 108\,\% & 102\,\% & 101\,\% & 103\,\% \\
Drand48Mix & 110\,\% & 112\,\% & 116\,\% & 115\,\% & 100\,\% & 100\,\% & 107\,\% \\
ThreadLocalRandomSlow & 112\,\% & 115\,\% & 111\,\% & 112\,\% & 104\,\% & 102\,\% & 108\,\% \\
\end{tabular}
\end{table}

In [25]:

s = df_time.style.format("{:.0f}%").set_caption("Times to generate PRN (Normalized to fastest in each column)").set_table_styles([{
    "selector": "caption",
    "props": []
}])
print(s.to_html())

<style type="text/css">
#T_cf038 caption {
}
</style>
<table id="T_cf038">
  <caption>Times to generate PRN (Normalized to fastest in each column)</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_cf038_level0_col0" class="col_heading level0 col0" >Exponential</th>
      <th id="T_cf038_level0_col1" class="col_heading level0 col1" >Log-Normal</th>
      <th id="T_cf038_level0_col2" class="col_heading level0 col2" >Gamma</th>
      <th id="T_cf038_level0_col3" class="col_heading level0 col3" >Triangular</th>
      <th id="T_cf038_level0_col4" class="col_heading level0 col4" >Poisson</th>
      <th id="T_cf038_level0_col5" class="col_heading level0 col5" >Geometric</th>
      <th id="T_cf038_level0_col6" class="col_heading level0 col6" >Average</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_cf038_level0_row0" class="row_heading level0 row0" >ThreadLocalRandom</th>
      <td id="T_cf038_row0_col0" class="data row0 col0" >107%</td>
      <td id="T_cf038_row0_col1" class="data row0 col1" >100%</td>
      <td id="T_cf038_row0_col2" class="data row0 col2" >100%</td>
      <td id="T_cf038_row0_col3" class="data row0 col3" >107%</td>
      <td id="T_cf038_row0_col4" class="data row0 col4" >100%</td>
      <td id="T_cf038_row0_col5" class="data row0 col5" >103%</td>
      <td id="T_cf038_row0_col6" class="data row0 col6" >101%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row1" class="row_heading level0 row1" >Random</th>
      <td id="T_cf038_row1_col0" class="data row1 col0" >108%</td>
      <td id="T_cf038_row1_col1" class="data row1 col1" >102%</td>
      <td id="T_cf038_row1_col2" class="data row1 col2" >104%</td>
      <td id="T_cf038_row1_col3" class="data row1 col3" >107%</td>
      <td id="T_cf038_row1_col4" class="data row1 col4" >101%</td>
      <td id="T_cf038_row1_col5" class="data row1 col5" >105%</td>
      <td id="T_cf038_row1_col6" class="data row1 col6" >103%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row2" class="row_heading level0 row2" >SecureRandom</th>
      <td id="T_cf038_row2_col0" class="data row2 col0" >377%</td>
      <td id="T_cf038_row2_col1" class="data row2 col1" >412%</td>
      <td id="T_cf038_row2_col2" class="data row2 col2" >650%</td>
      <td id="T_cf038_row2_col3" class="data row2 col3" >370%</td>
      <td id="T_cf038_row2_col4" class="data row2 col4" >283%</td>
      <td id="T_cf038_row2_col5" class="data row2 col5" >361%</td>
      <td id="T_cf038_row2_col6" class="data row2 col6" >396%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row3" class="row_heading level0 row3" >Well512a</th>
      <td id="T_cf038_row3_col0" class="data row3 col0" >109%</td>
      <td id="T_cf038_row3_col1" class="data row3 col1" >109%</td>
      <td id="T_cf038_row3_col2" class="data row3 col2" >117%</td>
      <td id="T_cf038_row3_col3" class="data row3 col3" >113%</td>
      <td id="T_cf038_row3_col4" class="data row3 col4" >102%</td>
      <td id="T_cf038_row3_col5" class="data row3 col5" >103%</td>
      <td id="T_cf038_row3_col6" class="data row3 col6" >107%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row4" class="row_heading level0 row4" >Well1024a</th>
      <td id="T_cf038_row4_col0" class="data row4 col0" >109%</td>
      <td id="T_cf038_row4_col1" class="data row4 col1" >107%</td>
      <td id="T_cf038_row4_col2" class="data row4 col2" >117%</td>
      <td id="T_cf038_row4_col3" class="data row4 col3" >114%</td>
      <td id="T_cf038_row4_col4" class="data row4 col4" >102%</td>
      <td id="T_cf038_row4_col5" class="data row4 col5" >116%</td>
      <td id="T_cf038_row4_col6" class="data row4 col6" >109%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row5" class="row_heading level0 row5" >Well19937a</th>
      <td id="T_cf038_row5_col0" class="data row5 col0" >110%</td>
      <td id="T_cf038_row5_col1" class="data row5 col1" >113%</td>
      <td id="T_cf038_row5_col2" class="data row5 col2" >123%</td>
      <td id="T_cf038_row5_col3" class="data row5 col3" >117%</td>
      <td id="T_cf038_row5_col4" class="data row5 col4" >104%</td>
      <td id="T_cf038_row5_col5" class="data row5 col5" >108%</td>
      <td id="T_cf038_row5_col6" class="data row5 col6" >111%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row6" class="row_heading level0 row6" >Well19937c</th>
      <td id="T_cf038_row6_col0" class="data row6 col0" >111%</td>
      <td id="T_cf038_row6_col1" class="data row6 col1" >112%</td>
      <td id="T_cf038_row6_col2" class="data row6 col2" >127%</td>
      <td id="T_cf038_row6_col3" class="data row6 col3" >117%</td>
      <td id="T_cf038_row6_col4" class="data row6 col4" >106%</td>
      <td id="T_cf038_row6_col5" class="data row6 col5" >108%</td>
      <td id="T_cf038_row6_col6" class="data row6 col6" >112%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row7" class="row_heading level0 row7" >Well44497a</th>
      <td id="T_cf038_row7_col0" class="data row7 col0" >111%</td>
      <td id="T_cf038_row7_col1" class="data row7 col1" >114%</td>
      <td id="T_cf038_row7_col2" class="data row7 col2" >125%</td>
      <td id="T_cf038_row7_col3" class="data row7 col3" >116%</td>
      <td id="T_cf038_row7_col4" class="data row7 col4" >107%</td>
      <td id="T_cf038_row7_col5" class="data row7 col5" >110%</td>
      <td id="T_cf038_row7_col6" class="data row7 col6" >112%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row8" class="row_heading level0 row8" >Well44497b</th>
      <td id="T_cf038_row8_col0" class="data row8 col0" >113%</td>
      <td id="T_cf038_row8_col1" class="data row8 col1" >113%</td>
      <td id="T_cf038_row8_col2" class="data row8 col2" >127%</td>
      <td id="T_cf038_row8_col3" class="data row8 col3" >116%</td>
      <td id="T_cf038_row8_col4" class="data row8 col4" >106%</td>
      <td id="T_cf038_row8_col5" class="data row8 col5" >108%</td>
      <td id="T_cf038_row8_col6" class="data row8 col6" >112%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row9" class="row_heading level0 row9" >MersenneTwister</th>
      <td id="T_cf038_row9_col0" class="data row9 col0" >108%</td>
      <td id="T_cf038_row9_col1" class="data row9 col1" >109%</td>
      <td id="T_cf038_row9_col2" class="data row9 col2" >119%</td>
      <td id="T_cf038_row9_col3" class="data row9 col3" >111%</td>
      <td id="T_cf038_row9_col4" class="data row9 col4" >105%</td>
      <td id="T_cf038_row9_col5" class="data row9 col5" >106%</td>
      <td id="T_cf038_row9_col6" class="data row9 col6" >108%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row10" class="row_heading level0 row10" >SFC64</th>
      <td id="T_cf038_row10_col0" class="data row10 col0" >100%</td>
      <td id="T_cf038_row10_col1" class="data row10 col1" >104%</td>
      <td id="T_cf038_row10_col2" class="data row10 col2" >103%</td>
      <td id="T_cf038_row10_col3" class="data row10 col3" >100%</td>
      <td id="T_cf038_row10_col4" class="data row10 col4" >100%</td>
      <td id="T_cf038_row10_col5" class="data row10 col5" >100%</td>
      <td id="T_cf038_row10_col6" class="data row10 col6" >100%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row11" class="row_heading level0 row11" >ISAAC</th>
      <td id="T_cf038_row11_col0" class="data row11 col0" >109%</td>
      <td id="T_cf038_row11_col1" class="data row11 col1" >108%</td>
      <td id="T_cf038_row11_col2" class="data row11 col2" >122%</td>
      <td id="T_cf038_row11_col3" class="data row11 col3" >113%</td>
      <td id="T_cf038_row11_col4" class="data row11 col4" >103%</td>
      <td id="T_cf038_row11_col5" class="data row11 col5" >107%</td>
      <td id="T_cf038_row11_col6" class="data row11 col6" >109%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row12" class="row_heading level0 row12" >XoRoShiRo128++</th>
      <td id="T_cf038_row12_col0" class="data row12 col0" >103%</td>
      <td id="T_cf038_row12_col1" class="data row12 col1" >107%</td>
      <td id="T_cf038_row12_col2" class="data row12 col2" >112%</td>
      <td id="T_cf038_row12_col3" class="data row12 col3" >113%</td>
      <td id="T_cf038_row12_col4" class="data row12 col4" >101%</td>
      <td id="T_cf038_row12_col5" class="data row12 col5" >102%</td>
      <td id="T_cf038_row12_col6" class="data row12 col6" >105%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row13" class="row_heading level0 row13" >XoRoShiRo128**</th>
      <td id="T_cf038_row13_col0" class="data row13 col0" >101%</td>
      <td id="T_cf038_row13_col1" class="data row13 col1" >104%</td>
      <td id="T_cf038_row13_col2" class="data row13 col2" >113%</td>
      <td id="T_cf038_row13_col3" class="data row13 col3" >110%</td>
      <td id="T_cf038_row13_col4" class="data row13 col4" >101%</td>
      <td id="T_cf038_row13_col5" class="data row13 col5" >103%</td>
      <td id="T_cf038_row13_col6" class="data row13 col6" >104%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row14" class="row_heading level0 row14" >XoRoShiRo64**</th>
      <td id="T_cf038_row14_col0" class="data row14 col0" >101%</td>
      <td id="T_cf038_row14_col1" class="data row14 col1" >107%</td>
      <td id="T_cf038_row14_col2" class="data row14 col2" >115%</td>
      <td id="T_cf038_row14_col3" class="data row14 col3" >110%</td>
      <td id="T_cf038_row14_col4" class="data row14 col4" >100%</td>
      <td id="T_cf038_row14_col5" class="data row14 col5" >103%</td>
      <td id="T_cf038_row14_col6" class="data row14 col6" >104%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row15" class="row_heading level0 row15" >XoRoShiRo256++</th>
      <td id="T_cf038_row15_col0" class="data row15 col0" >117%</td>
      <td id="T_cf038_row15_col1" class="data row15 col1" >121%</td>
      <td id="T_cf038_row15_col2" class="data row15 col2" >122%</td>
      <td id="T_cf038_row15_col3" class="data row15 col3" >122%</td>
      <td id="T_cf038_row15_col4" class="data row15 col4" >108%</td>
      <td id="T_cf038_row15_col5" class="data row15 col5" >117%</td>
      <td id="T_cf038_row15_col6" class="data row15 col6" >116%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row16" class="row_heading level0 row16" >XoRoShiRo1024++</th>
      <td id="T_cf038_row16_col0" class="data row16 col0" >104%</td>
      <td id="T_cf038_row16_col1" class="data row16 col1" >109%</td>
      <td id="T_cf038_row16_col2" class="data row16 col2" >107%</td>
      <td id="T_cf038_row16_col3" class="data row16 col3" >104%</td>
      <td id="T_cf038_row16_col4" class="data row16 col4" >102%</td>
      <td id="T_cf038_row16_col5" class="data row16 col5" >101%</td>
      <td id="T_cf038_row16_col6" class="data row16 col6" >103%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row17" class="row_heading level0 row17" >XoRoShiRo1024*</th>
      <td id="T_cf038_row17_col0" class="data row17 col0" >107%</td>
      <td id="T_cf038_row17_col1" class="data row17 col1" >109%</td>
      <td id="T_cf038_row17_col2" class="data row17 col2" >108%</td>
      <td id="T_cf038_row17_col3" class="data row17 col3" >105%</td>
      <td id="T_cf038_row17_col4" class="data row17 col4" >103%</td>
      <td id="T_cf038_row17_col5" class="data row17 col5" >101%</td>
      <td id="T_cf038_row17_col6" class="data row17 col6" >104%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row18" class="row_heading level0 row18" >XoRoShiRo1024**</th>
      <td id="T_cf038_row18_col0" class="data row18 col0" >108%</td>
      <td id="T_cf038_row18_col1" class="data row18 col1" >110%</td>
      <td id="T_cf038_row18_col2" class="data row18 col2" >109%</td>
      <td id="T_cf038_row18_col3" class="data row18 col3" >106%</td>
      <td id="T_cf038_row18_col4" class="data row18 col4" >102%</td>
      <td id="T_cf038_row18_col5" class="data row18 col5" >104%</td>
      <td id="T_cf038_row18_col6" class="data row18 col6" >105%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row19" class="row_heading level0 row19" >L32X64Mix</th>
      <td id="T_cf038_row19_col0" class="data row19 col0" >105%</td>
      <td id="T_cf038_row19_col1" class="data row19 col1" >105%</td>
      <td id="T_cf038_row19_col2" class="data row19 col2" >114%</td>
      <td id="T_cf038_row19_col3" class="data row19 col3" >110%</td>
      <td id="T_cf038_row19_col4" class="data row19 col4" >102%</td>
      <td id="T_cf038_row19_col5" class="data row19 col5" >104%</td>
      <td id="T_cf038_row19_col6" class="data row19 col6" >105%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row20" class="row_heading level0 row20" >L64X128Mix</th>
      <td id="T_cf038_row20_col0" class="data row20 col0" >119%</td>
      <td id="T_cf038_row20_col1" class="data row20 col1" >123%</td>
      <td id="T_cf038_row20_col2" class="data row20 col2" >124%</td>
      <td id="T_cf038_row20_col3" class="data row20 col3" >123%</td>
      <td id="T_cf038_row20_col4" class="data row20 col4" >109%</td>
      <td id="T_cf038_row20_col5" class="data row20 col5" >116%</td>
      <td id="T_cf038_row20_col6" class="data row20 col6" >117%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row21" class="row_heading level0 row21" >L64X128**</th>
      <td id="T_cf038_row21_col0" class="data row21 col0" >123%</td>
      <td id="T_cf038_row21_col1" class="data row21 col1" >122%</td>
      <td id="T_cf038_row21_col2" class="data row21 col2" >126%</td>
      <td id="T_cf038_row21_col3" class="data row21 col3" >122%</td>
      <td id="T_cf038_row21_col4" class="data row21 col4" >111%</td>
      <td id="T_cf038_row21_col5" class="data row21 col5" >117%</td>
      <td id="T_cf038_row21_col6" class="data row21 col6" >118%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row22" class="row_heading level0 row22" >L64X256Mix</th>
      <td id="T_cf038_row22_col0" class="data row22 col0" >125%</td>
      <td id="T_cf038_row22_col1" class="data row22 col1" >123%</td>
      <td id="T_cf038_row22_col2" class="data row22 col2" >127%</td>
      <td id="T_cf038_row22_col3" class="data row22 col3" >123%</td>
      <td id="T_cf038_row22_col4" class="data row22 col4" >112%</td>
      <td id="T_cf038_row22_col5" class="data row22 col5" >119%</td>
      <td id="T_cf038_row22_col6" class="data row22 col6" >119%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row23" class="row_heading level0 row23" >L64X1024Mix</th>
      <td id="T_cf038_row23_col0" class="data row23 col0" >127%</td>
      <td id="T_cf038_row23_col1" class="data row23 col1" >124%</td>
      <td id="T_cf038_row23_col2" class="data row23 col2" >128%</td>
      <td id="T_cf038_row23_col3" class="data row23 col3" >124%</td>
      <td id="T_cf038_row23_col4" class="data row23 col4" >112%</td>
      <td id="T_cf038_row23_col5" class="data row23 col5" >119%</td>
      <td id="T_cf038_row23_col6" class="data row23 col6" >120%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row24" class="row_heading level0 row24" >L128X128Mix</th>
      <td id="T_cf038_row24_col0" class="data row24 col0" >124%</td>
      <td id="T_cf038_row24_col1" class="data row24 col1" >124%</td>
      <td id="T_cf038_row24_col2" class="data row24 col2" >128%</td>
      <td id="T_cf038_row24_col3" class="data row24 col3" >126%</td>
      <td id="T_cf038_row24_col4" class="data row24 col4" >112%</td>
      <td id="T_cf038_row24_col5" class="data row24 col5" >119%</td>
      <td id="T_cf038_row24_col6" class="data row24 col6" >120%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row25" class="row_heading level0 row25" >L128X256Mix</th>
      <td id="T_cf038_row25_col0" class="data row25 col0" >122%</td>
      <td id="T_cf038_row25_col1" class="data row25 col1" >123%</td>
      <td id="T_cf038_row25_col2" class="data row25 col2" >128%</td>
      <td id="T_cf038_row25_col3" class="data row25 col3" >126%</td>
      <td id="T_cf038_row25_col4" class="data row25 col4" >113%</td>
      <td id="T_cf038_row25_col5" class="data row25 col5" >120%</td>
      <td id="T_cf038_row25_col6" class="data row25 col6" >120%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row26" class="row_heading level0 row26" >L128X1024Mix</th>
      <td id="T_cf038_row26_col0" class="data row26 col0" >124%</td>
      <td id="T_cf038_row26_col1" class="data row26 col1" >124%</td>
      <td id="T_cf038_row26_col2" class="data row26 col2" >129%</td>
      <td id="T_cf038_row26_col3" class="data row26 col3" >126%</td>
      <td id="T_cf038_row26_col4" class="data row26 col4" >112%</td>
      <td id="T_cf038_row26_col5" class="data row26 col5" >121%</td>
      <td id="T_cf038_row26_col6" class="data row26 col6" >120%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row27" class="row_heading level0 row27" >PcgRxsMXs64</th>
      <td id="T_cf038_row27_col0" class="data row27 col0" >108%</td>
      <td id="T_cf038_row27_col1" class="data row27 col1" >110%</td>
      <td id="T_cf038_row27_col2" class="data row27 col2" >109%</td>
      <td id="T_cf038_row27_col3" class="data row27 col3" >106%</td>
      <td id="T_cf038_row27_col4" class="data row27 col4" >103%</td>
      <td id="T_cf038_row27_col5" class="data row27 col5" >102%</td>
      <td id="T_cf038_row27_col6" class="data row27 col6" >105%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row28" class="row_heading level0 row28" >Philox4x64</th>
      <td id="T_cf038_row28_col0" class="data row28 col0" >110%</td>
      <td id="T_cf038_row28_col1" class="data row28 col1" >114%</td>
      <td id="T_cf038_row28_col2" class="data row28 col2" >111%</td>
      <td id="T_cf038_row28_col3" class="data row28 col3" >108%</td>
      <td id="T_cf038_row28_col4" class="data row28 col4" >104%</td>
      <td id="T_cf038_row28_col5" class="data row28 col5" >106%</td>
      <td id="T_cf038_row28_col6" class="data row28 col6" >107%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row29" class="row_heading level0 row29" >Drand48</th>
      <td id="T_cf038_row29_col0" class="data row29 col0" >101%</td>
      <td id="T_cf038_row29_col1" class="data row29 col1" >105%</td>
      <td id="T_cf038_row29_col2" class="data row29 col2" >109%</td>
      <td id="T_cf038_row29_col3" class="data row29 col3" >108%</td>
      <td id="T_cf038_row29_col4" class="data row29 col4" >102%</td>
      <td id="T_cf038_row29_col5" class="data row29 col5" >101%</td>
      <td id="T_cf038_row29_col6" class="data row29 col6" >103%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row30" class="row_heading level0 row30" >Drand48Mix</th>
      <td id="T_cf038_row30_col0" class="data row30 col0" >110%</td>
      <td id="T_cf038_row30_col1" class="data row30 col1" >112%</td>
      <td id="T_cf038_row30_col2" class="data row30 col2" >116%</td>
      <td id="T_cf038_row30_col3" class="data row30 col3" >115%</td>
      <td id="T_cf038_row30_col4" class="data row30 col4" >100%</td>
      <td id="T_cf038_row30_col5" class="data row30 col5" >100%</td>
      <td id="T_cf038_row30_col6" class="data row30 col6" >107%</td>
    </tr>
    <tr>
      <th id="T_cf038_level0_row31" class="row_heading level0 row31" >ThreadLocalRandomSlow</th>
      <td id="T_cf038_row31_col0" class="data row31 col0" >112%</td>
      <td id="T_cf038_row31_col1" class="data row31 col1" >115%</td>
      <td id="T_cf038_row31_col2" class="data row31 col2" >111%</td>
      <td id="T_cf038_row31_col3" class="data row31 col3" >112%</td>
      <td id="T_cf038_row31_col4" class="data row31 col4" >104%</td>
      <td id="T_cf038_row31_col5" class="data row31 col5" >102%</td>
      <td id="T_cf038_row31_col6" class="data row31 col6" >108%</td>
    </tr>
  </tbody>
</table>

In [28]:
generators

['ThreadLocalRandom',
 'Random',
 'SecureRandom',
 'Well512a',
 'Well1024a',
 'Well19937a',
 'Well19937c',
 'Well44497a',
 'Well44497b',
 'MersenneTwister',
 'SFC64',
 'ISAAC',
 'XoRoShiRo128++',
 'XoRoShiRo128**',
 'XoRoShiRo64**',
 'XoRoShiRo256++',
 'XoRoShiRo1024++',
 'XoRoShiRo1024*',
 'XoRoShiRo1024**',
 'L32X64Mix',
 'L64X128Mix',
 'L64X128**',
 'L64X256Mix',
 'L64X1024Mix',
 'L128X128Mix',
 'L128X256Mix',
 'L128X1024Mix',
 'PcgRxsMXs64',
 'Philox4x64',
 'Drand48',
 'Drand48Mix',
 'ThreadLocalRandomSlow']

In [32]:
print(data[0]["name"])
for i, generator in enumerate(generators):
    print(generator,round(data[0]["time"][i]/1000,2),sep="\t")

Exponential
ThreadLocalRandom	2.55
Random	2.59
SecureRandom	9.02
Well512a	2.6
Well1024a	2.6
Well19937a	2.64
Well19937c	2.66
Well44497a	2.66
Well44497b	2.69
MersenneTwister	2.59
SFC64	2.39
ISAAC	2.62
XoRoShiRo128++	2.46
XoRoShiRo128**	2.43
XoRoShiRo64**	2.43
XoRoShiRo256++	2.79
XoRoShiRo1024++	2.49
XoRoShiRo1024*	2.57
XoRoShiRo1024**	2.59
L32X64Mix	2.5
L64X128Mix	2.85
L64X128**	2.94
L64X256Mix	3.0
L64X1024Mix	3.03
L128X128Mix	2.97
L128X256Mix	2.93
L128X1024Mix	2.97
PcgRxsMXs64	2.57
Philox4x64	2.63
Drand48	2.42
Drand48Mix	2.63
ThreadLocalRandomSlow	2.69